PotatZap: Server/src/server/accept_cli.c File Reference
accept_cli.c File Reference
accept protocol for the server
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
Functions
void add_cli_to_ll (client_t *new_client, int client_socket)
int add_client (int client_socket)
Function that define the client parameters.
int accept_new_client (void)
Function that accept a new client connection.
Detailed Description
accept protocol for the server
Definition in file accept_cli.c.
Function Documentation
accept_new_client()
int accept_new_client (void)
Function that accept a new client connection.
Parameters
void no parameters are required.
will check if the client socket is ready and accept the new client connection.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 54 of file accept_cli.c.
 {
     server_t *server = get_instance();
     int new_socket = 0;
     if (FD_ISSET(server->socket, &server->readfs)) {
         new_socket = accept(server->socket, NULL, NULL);
         if (new_socket < 0) {
             perror("accept");
             return 84;
         }
         add_client(new_socket);
     }
     return 0;
 }
References add_client(), get_instance(), and server.
Referenced by run_server().
add_cli_to_ll()
void add_cli_to_ll (client_t * new_client, int client_socket)
Definition at line 18 of file accept_cli.c.
 {
     server_t *server = get_instance();
     client_t *cli = NULL;
     new_client->socket = client_socket;
     new_client->team = NULL;
     new_client->status = false;
     new_client->nb_commands = 0;
     new_client->next = NULL;
     if (server->clients == NULL) {
         server->clients = new_client;
     } else {
         cli = server->clients;
         while (cli->next != NULL){
             cli = cli->next;
         }
         cli->next = new_client;
     }
 }
References get_instance(), and server.
Referenced by add_client().
add_client()
int add_client (int client_socket)
Function that define the client parameters.
Parameters
client_t *new_client the new client.
int client_socket the socket of the client.
will define the client parameters.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 39 of file accept_cli.c.
 {
     client_t *new_client = malloc(sizeof(client_t));
     if (new_client == NULL) {
         perror("malloc");
         close(client_socket);
         return 84;
     }
     add_cli_to_ll(new_client, client_socket);
     printf("Added new client with socket %d\n", client_socket);
     write(new_client->socket, "WELCOME\r\n", strlen("WELCOME\r\n"));
     return 0;
 }
References add_cli_to_ll().
Referenced by accept_new_client().