PotatZap: test_zappy_ai.TestZappyAI Class Reference
test_zappy_ai.TestZappyAI Class Reference
Public Member Functions
def setUpClass (cls)
def setUp (self)
def tearDown (self)
def tearDownClass (cls)
def test_split_by_commas (self)
def test_find_keyword_in_list (self)
def test_count_words_at_index (self)
def test_remove_element (self)
def test_send_and_remove (self)
def test_going_forward (self)
def test_turning_right (self)
def test_turning_left (self)
def test_looking (self)
def test_check_stones (self)
def test_can_evolve (self, mock_send_and_remove)
def test_received_look (self)
def test_command_received (self)
def test_moving_level_one (self, mock_turning_right, mock_turning_left, mock_going_forward)
def test_moving_player (self, mock_moving_level_one)
def test_command_send (self, mock_looking)
Public Attributes
tests
success_count
failure_count
player
Detailed Description
Definition at line 31 of file test_zappy_ai.py.
Member Function Documentation
setUp()
def test_zappy_ai.TestZappyAI.setUp (self)
Definition at line 56 of file test_zappy_ai.py.
     def setUp(self):
         self.player = Player()
setUpClass()
def test_zappy_ai.TestZappyAI.setUpClass (cls)
Definition at line 34 of file test_zappy_ai.py.
     def setUpClass(cls):
         cls.tests = [
             'test_split_by_commas',
             'test_find_keyword_in_list',
             'test_count_words_at_index',
             'test_remove_element',
             'test_send_and_remove',
             'test_going_forward',
             'test_turning_right',
             'test_turning_left',
             'test_looking',
             'test_check_stones',
             'test_can_evolve',
             'test_received_look',
             'test_command_received',
             'test_moving_level_one',
             'test_moving_player',
             'test_command_send',
         ]
         cls.success_count = 0
         cls.failure_count = 0
tearDown()
def test_zappy_ai.TestZappyAI.tearDown (self)
Definition at line 59 of file test_zappy_ai.py.
     def tearDown(self):
         test_name = self._testMethodName
         result = self.defaultTestResult()
         self._feedErrorsToResult(result, self._outcome.errors)
         if any(error for (test, error) in result.errors):
             print(f"{test_name} ... FAILURE")
             TestZappyAI.failure_count += 1
         elif any(failure for (test, failure) in result.failures):
             print(f"{test_name} ... FAILURE")
             TestZappyAI.failure_count += 1
         else:
             print(f"{test_name} ... SUCCESS")
             TestZappyAI.success_count += 1
tearDownClass()
def test_zappy_ai.TestZappyAI.tearDownClass (cls)
Definition at line 74 of file test_zappy_ai.py.
     def tearDownClass(cls):
         print(f"\nTotal tests run: {len(cls.tests)}")
         print(f"Tests succeeded: {cls.success_count}")
         print(f"Tests failed: {cls.failure_count}")
test_can_evolve()
def test_zappy_ai.TestZappyAI.test_can_evolve (self, mock_send_and_remove)
Definition at line 134 of file test_zappy_ai.py.
     def test_can_evolve(self, mock_send_and_remove):
         client_socket = Mock()
         self.player.view = ["linemate"]
         self.assertTrue(can_evolve(client_socket, self.player))
         self.assertTrue(self.player.incanting)
References zappy_ai.can_evolve(), and test_zappy_ai.TestZappyAI.player.
test_check_stones()
def test_zappy_ai.TestZappyAI.test_check_stones (self)
Definition at line 127 of file test_zappy_ai.py.
     def test_check_stones(self):
         self.player.view = ["linemate", "deraumere"]
         self.assertEqual(check_stones(self.player, 0), "linemate")
         self.player.linemate = 9
         self.assertEqual(check_stones(self.player, 1), "deraumere")
References zappy_ai.check_stones(), and test_zappy_ai.TestZappyAI.player.
test_command_received()
def test_zappy_ai.TestZappyAI.test_command_received (self)
Definition at line 146 of file test_zappy_ai.py.
     def test_command_received(self):
         data_rec = Mock()
         data_rec.decode.return_value = "Current level: 2\n"
         self.player.queue.append("Incantation\n")
         command_received(self.player, data_rec)
         self.assertEqual(self.player.level, 2)
References zappy_ai.command_received(), and test_zappy_ai.TestZappyAI.player.
test_command_send()
def test_zappy_ai.TestZappyAI.test_command_send (self, mock_looking)
Definition at line 170 of file test_zappy_ai.py.
     def test_command_send(self, mock_looking):
         client_socket = Mock()
         self.player.look = False
         command_send(client_socket, self.player)
         mock_looking.assert_called()
References zappy_ai.command_send(), and test_zappy_ai.TestZappyAI.player.
test_count_words_at_index()
def test_zappy_ai.TestZappyAI.test_count_words_at_index (self)
Definition at line 86 of file test_zappy_ai.py.
     def test_count_words_at_index(self):
         strings = ["hello egg player", "hello world", "foo bar egg player"]
         self.assertEqual(count_words_at_index(strings, 0), 1)
         self.assertEqual(count_words_at_index(strings, 1), 2)
         self.assertEqual(count_words_at_index(strings, 2), 2)
References zappy_ai.count_words_at_index().
test_find_keyword_in_list()
def test_zappy_ai.TestZappyAI.test_find_keyword_in_list (self)
Definition at line 82 of file test_zappy_ai.py.
     def test_find_keyword_in_list(self):
         strings = ["apple", "banana", "cherry", "date", "apple pie"]
         self.assertEqual(find_keyword_in_list(strings, "apple"), [0, 4])
References zappy_ai.find_keyword_in_list().
test_going_forward()
def test_zappy_ai.TestZappyAI.test_going_forward (self)
Definition at line 104 of file test_zappy_ai.py.
     def test_going_forward(self):
         client_socket = Mock()
         going_forward(client_socket, self.player)
         client_socket.send.assert_called_with(b"Forward\n")
         self.assertFalse(self.player.look)
         self.assertEqual(self.player.view, [])
References zappy_ai.going_forward(), and test_zappy_ai.TestZappyAI.player.
test_looking()
def test_zappy_ai.TestZappyAI.test_looking (self)
Definition at line 121 of file test_zappy_ai.py.
     def test_looking(self):
         client_socket = Mock()
         looking(client_socket, self.player)
         client_socket.send.assert_called_with(b"Look\n")
         self.assertTrue(self.player.look)
References zappy_ai.looking(), and test_zappy_ai.TestZappyAI.player.
test_moving_level_one()
def test_zappy_ai.TestZappyAI.test_moving_level_one (self, mock_turning_right, mock_turning_left, mock_going_forward)
Definition at line 156 of file test_zappy_ai.py.
     def test_moving_level_one(self, mock_turning_right, mock_turning_left, mock_going_forward):
         client_socket = Mock()
         self.player.view = ["", "", "foo"]
         moving_level_one(client_socket, self.player)
         mock_going_forward.assert_called()
References test_zappy_ai.TestZappyAI.player.
test_moving_player()
def test_zappy_ai.TestZappyAI.test_moving_player (self, mock_moving_level_one)
Definition at line 163 of file test_zappy_ai.py.
     def test_moving_player(self, mock_moving_level_one):
         client_socket = Mock()
         self.player.level = 1
         moving_player(client_socket, self.player)
         mock_moving_level_one.assert_called()
References zappy_ai.moving_player(), and test_zappy_ai.TestZappyAI.player.
test_received_look()
def test_zappy_ai.TestZappyAI.test_received_look (self)
Definition at line 140 of file test_zappy_ai.py.
     def test_received_look(self):
         data_rec = Mock()
         data_rec.decode.return_value = "[linemate, deraumere]"
         received_look(self.player, data_rec)
         self.assertEqual(self.player.view, ["linemate", "deraumere"])
References test_zappy_ai.TestZappyAI.player, and zappy_ai.received_look().
test_remove_element()
def test_zappy_ai.TestZappyAI.test_remove_element (self)
Definition at line 92 of file test_zappy_ai.py.
     def test_remove_element(self):
         strings = ["hello world", "foo bar"]
         remove_element(strings, 0, "world")
         self.assertEqual(strings, ["hello ", "foo bar"])
References zappy_ai.remove_element().
test_send_and_remove()
def test_zappy_ai.TestZappyAI.test_send_and_remove (self)
Definition at line 97 of file test_zappy_ai.py.
     def test_send_and_remove(self):
         client_socket = Mock()
         self.player.view = ["food", "linemate"]
         send_and_remove(client_socket, self.player, 0, "food")
         client_socket.send.assert_called_with(b"Take food\n")
         self.assertEqual(self.player.view, ["", "linemate"])
References test_zappy_ai.TestZappyAI.player, and zappy_ai.send_and_remove().
test_split_by_commas()
def test_zappy_ai.TestZappyAI.test_split_by_commas (self)
Definition at line 79 of file test_zappy_ai.py.
     def test_split_by_commas(self):
         self.assertEqual(split_by_commas('[a, b, c]'), ['a', 'b', 'c'])
References zappy_ai.split_by_commas().
test_turning_left()
def test_zappy_ai.TestZappyAI.test_turning_left (self)
Definition at line 116 of file test_zappy_ai.py.
     def test_turning_left(self):
         client_socket = Mock()
         turning_left(client_socket, self.player)
         client_socket.send.assert_called_with(b"Left\n")
References test_zappy_ai.TestZappyAI.player, and zappy_ai.turning_left().
test_turning_right()
def test_zappy_ai.TestZappyAI.test_turning_right (self)
Definition at line 111 of file test_zappy_ai.py.
     def test_turning_right(self):
         client_socket = Mock()
         turning_right(client_socket, self.player)
         client_socket.send.assert_called_with(b"Right\n")
References test_zappy_ai.TestZappyAI.player, and zappy_ai.turning_right().
Member Data Documentation
failure_count
test_zappy_ai.TestZappyAI.failure_count
Definition at line 54 of file test_zappy_ai.py.
player
test_zappy_ai.TestZappyAI.player
Definition at line 57 of file test_zappy_ai.py.
Referenced by test_zappy_ai.TestZappyAI.test_can_evolve(), test_zappy_ai.TestZappyAI.test_check_stones(), test_zappy_ai.TestZappyAI.test_command_received(), test_zappy_ai.TestZappyAI.test_command_send(), test_zappy_ai.TestZappyAI.test_going_forward(), test_zappy_ai.TestZappyAI.test_looking(), test_zappy_ai.TestZappyAI.test_moving_level_one(), test_zappy_ai.TestZappyAI.test_moving_player(), test_zappy_ai.TestZappyAI.test_received_look(), test_zappy_ai.TestZappyAI.test_send_and_remove(), test_zappy_ai.TestZappyAI.test_turning_left(), and test_zappy_ai.TestZappyAI.test_turning_right().
success_count
test_zappy_ai.TestZappyAI.success_count
Definition at line 53 of file test_zappy_ai.py.
tests
test_zappy_ai.TestZappyAI.tests
Definition at line 35 of file test_zappy_ai.py.
The documentation for this class was generated from the following file:
IA/tests/unit-tests/test_zappy_ai.py