PotatZap: Server Class Reference
Server Class Reference
#include <Server.hpp>
Public Member Functions
Server ()
int connect_server (const std::string &port, const std::string &host)
void stop ()
void send_data (const std::string &data)
void start_receive ()
Public Attributes
std::function< void(const std::string &)> on_receive
Private Member Functions
void handle_connect (const boost::system::error_code &error)
void handle_write (const boost::system::error_code &error, std::size_t bytes_transferred)
void handle_read (const boost::system::error_code &error, std::size_t bytes_transferred)
void do_write ()
Private Attributes
boost::asio::io_context io_context
tcp::resolver resolver
tcp::socket socket
boost::asio::streambuf buffer
std::thread net_thread
std::deque< std::string > write_msgs_
Detailed Description
Definition at line 20 of file Server.hpp.
Constructor & Destructor Documentation
Server()
Server::Server ()
Definition at line 10 of file Server.cpp.
 : resolver(io_context), socket(io_context) {}
Member Function Documentation
connect_server()
int Server::connect_server (const std::string & port, const std::string & host)
Definition at line 12 of file Server.cpp.
{
     try {
         tcp::resolver::results_type endpoints = resolver.resolve(host, port);
         boost::asio::async_connect(socket, endpoints,
             [this](const boost::system::error_code& error, const tcp::endpoint&) {
                 handle_connect(error);
             });
         // Run io_context in a separate thread
         net_thread = std::thread([this]() { io_context.run(); });
     } catch (const boost::system::system_error& e) {
         std::cerr << "Error: " << e.what() << std::endl;
         return 1;
     }
     return 0;
 }
References handle_connect(), io_context, net_thread, resolver, and socket.
do_write()
void Server::do_write () private
Definition at line 69 of file Server.cpp.
                       {
     boost::asio::async_write(socket,
         boost::asio::buffer(write_msgs_.front()),
         [this](const boost::system::error_code& error, std::size_t bytes_transferred) {
             if (!error) {
                 std::cout << "Data sent: " << bytes_transferred << std::endl;
                 write_msgs_.pop_front();
                 if (!write_msgs_.empty()) {
                     do_write();
                 }
             } else {
                 std::cerr << "Send failed: " << error.message() << std::endl;
             }
         });
 }
References socket, and write_msgs_.
Referenced by send_data().
handle_connect()
void Server::handle_connect (const boost::system::error_code & error) private
Definition at line 55 of file Server.cpp.
{
     if (!error) {
         std::cout << "Connected to server" << std::endl;
         // Initial authentication message
         send_data("GRAPHIC\n");
         // Start receiving data from the server
         start_receive();
     } else {
         std::cerr << "Connect failed: " << error.message() << std::endl;
     }
 }
References send_data(), and start_receive().
Referenced by connect_server().
handle_read()
void Server::handle_read (const boost::system::error_code & error, std::size_t bytes_transferred) private
Definition at line 85 of file Server.cpp.
{
     if (!error || error == boost::asio::error::eof) {
         std::string response(boost::asio::buffers_begin(buffer.data()), boost::asio::buffers_begin(buffer.data()) + bytes_transferred);
         buffer.consume(bytes_transferred); // Clear buffer after reading
         if (on_receive) {
             on_receive(response);  // Call the callback with the received data
         }
         // Continue to receive data
         start_receive();
     } else {
         std::cerr << "Receive failed: " << error.message() << std::endl;
     }
 }
References buffer, on_receive, and start_receive().
Referenced by start_receive().
handle_write()
void Server::handle_write (const boost::system::error_code & error, std::size_t bytes_transferred) private
send_data()
void Server::send_data (const std::string & data)
Definition at line 38 of file Server.cpp.
{
     boost::asio::post(io_context, [this, data]() {
         bool write_in_progress = !write_msgs_.empty();
         write_msgs_.push_back(data);
         if (!write_in_progress) {
             do_write();
         }
     });
 }
References do_write(), io_context, and write_msgs_.
Referenced by handle_connect().
start_receive()
void Server::start_receive ()
Definition at line 48 of file Server.cpp.
{
     boost::asio::async_read_until(socket, buffer, '\n',
         [this](const boost::system::error_code& error, std::size_t bytes_transferred) {
             handle_read(error, bytes_transferred);
         });
 }
References buffer, handle_read(), and socket.
Referenced by handle_connect(), and handle_read().
stop()
void Server::stop ()
Definition at line 31 of file Server.cpp.
                   {
     io_context.stop();
     if (net_thread.joinable()) {
         net_thread.join();
     }
 }
References io_context, and net_thread.
Member Data Documentation
buffer
boost::asio::streambuf Server::buffer private
Definition at line 39 of file Server.hpp.
Referenced by handle_read(), and start_receive().
io_context
boost::asio::io_context Server::io_context private
Definition at line 36 of file Server.hpp.
Referenced by connect_server(), send_data(), and stop().
net_thread
std::thread Server::net_thread private
Definition at line 40 of file Server.hpp.
Referenced by connect_server(), and stop().
on_receive
std::function<void(const std::string&)> Server::on_receive
Definition at line 28 of file Server.hpp.
Referenced by handle_read().
resolver
tcp::resolver Server::resolver private
Definition at line 37 of file Server.hpp.
Referenced by connect_server().
socket
tcp::socket Server::socket private
Definition at line 38 of file Server.hpp.
Referenced by connect_server(), do_write(), and start_receive().
write_msgs_
std::deque<std::string> Server::write_msgs_ private
Definition at line 41 of file Server.hpp.
Referenced by do_write(), and send_data().
The documentation for this class was generated from the following files:
Graphic/src/Server/Server.hpp
Graphic/src/Server/Server.cpp