PotatZap: Player Class Reference
Player Class Reference
#include <Player.hpp>
Public Member Functions
Player (int number, int posX, int posY, std::string teamName, Orientation orientation, int level=1)
~Player ()
int getNumber () const
int getPosX () const
int getPosY () const
int getLevel () const
std::string getTeamName ()
Orientation getOrientation ()
PlayerData getPlayerData ()
Private Attributes
PlayerData _playerData
Detailed Description
Definition at line 16 of file Player.hpp.
Constructor & Destructor Documentation
Player()
Player::Player (int number, int posX, int posY, std::string teamName, Orientation orientation, int level = 1)
Definition at line 10 of file Player.cpp.
 {
     _playerData._number = number;
     _playerData._posX = posX;
     _playerData._posY = posY;
     _playerData._level = lvl;
     _playerData._teamName = teamName;
     _playerData._orientation = orientation;
 }
References PlayerData::_level, PlayerData::_number, PlayerData::_orientation, _playerData, PlayerData::_posX, PlayerData::_posY, and PlayerData::_teamName.
~Player()
Player::~Player ()
Definition at line 20 of file Player.cpp.
 {}
Member Function Documentation
getLevel()
int Player::getLevel () const
Definition at line 37 of file Player.cpp.
 {
     return _playerData._level;
 }
References PlayerData::_level, and _playerData.
Referenced by Test().
getNumber()
int Player::getNumber () const
Definition at line 22 of file Player.cpp.
 {
     return _playerData._number;
 }
References PlayerData::_number, and _playerData.
Referenced by Team::removePlayer(), and Test().
getOrientation()
Orientation Player::getOrientation ()
Definition at line 47 of file Player.cpp.
 {
     return _playerData._orientation;
 }
References PlayerData::_orientation, and _playerData.
Referenced by Test().
getPlayerData()
PlayerData Player::getPlayerData ()
Definition at line 52 of file Player.cpp.
 {
     return _playerData;
 }
References _playerData.
Referenced by Test().
getPosX()
int Player::getPosX () const
Definition at line 27 of file Player.cpp.
 {
     return _playerData._posX;
 }
References _playerData, and PlayerData::_posX.
Referenced by Test().
getPosY()
int Player::getPosY () const
Definition at line 32 of file Player.cpp.
 {
     return _playerData._posY;
 }
References _playerData, and PlayerData::_posY.
Referenced by Test().
getTeamName()
std::string Player::getTeamName ()
Definition at line 42 of file Player.cpp.
 {
     return _playerData._teamName;
 }
References _playerData, and PlayerData::_teamName.
Referenced by Test().
Member Data Documentation
_playerData
PlayerData Player::_playerData private
Definition at line 29 of file Player.hpp.
Referenced by getLevel(), getNumber(), getOrientation(), getPlayerData(), getPosX(), getPosY(), getTeamName(), and Player().
The documentation for this class was generated from the following files:
Graphic/src/Player/Player.hpp
Graphic/src/Player/Player.cpp