PotatZap: Server/include/get_instance.h File Reference
get_instance.h File Reference
get the server, map and game instances prototypes
#include "my.h"
#include "struct_server.h"
#include "struct_map.h"
#include "struct_client.h"
#include "struct_game.h"
Functions
server_t * get_instance (void)
Function that return the server instance.
map_t * get_map_instance (void)
Function that return the map instance.
game_t * get_game_instance (void)
Function that return the game instance.
Detailed Description
get the server, map and game instances prototypes
Definition in file get_instance.h.
Function Documentation
get_game_instance()
game_t* get_game_instance (void)
Function that return the game instance.
Parameters
void
will return an instance of the game(singleton).
Returns
game_t * return the game instance.
Definition at line 32 of file get_instance.c.
 {
     static game_t game;
     return &game;
 }
References game.
Referenced by detect_execution_time(), detect_team_validity(), handle_c(), handle_f(), handle_flags(), handle_n(), handle_team_full(), handle_x(), handle_y(), n_flag_detection(), put_c_flag(), select_function(), setup(), setup_command_collect(), setup_remove_cli(), setup_sending_cli_answers(), and Test().
get_instance()
server_t* get_instance (void)
Function that return the server instance.
Parameters
void
will return an instance of the server(singleton).
Returns
server_t * return the server instance.
Definition at line 18 of file get_instance.c.
 {
     static server_t server;
     return &server;
 }
References server.
Referenced by accept_new_client(), add_cli_to_ll(), add_cmd_to_ll(), add_to_waiting_list(), detect_client_waiting(), execute_cli_cmd(), execute_cli_cmd_bis(), find_client_and_prev(), handle_clients(), handle_p(), handle_sigint(), init_server(), init_server_bis(), init_server_launch(), init_server_listen(), init_socket(), load_cli_and_exec(), max_cmd_cli(), remove_found_client(), run_server(), select_function(), select_loop(), setup(), setup_command_collect(), setup_remove_cli(), setup_sending_cli_answers(), setup_server(), and Test().
get_map_instance()
map_t* get_map_instance (void)
Function that return the map instance.
Parameters
void
will return an instance of the map(singleton).
Returns
map_t * return the map instance.
Definition at line 25 of file get_instance.c.
 {
     static map_t map;
     return &map;
 }
Referenced by Test().