PotatZap: Server/src/server/handling_game_command.c File Reference
handling_game_command.c File Reference
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
int comp_cmd (char *command_type)
Function to compare the command type.
int comp_cmd_bis (char *command_type)
Function to compare the command type.
void execute_game_cmd (int cli_socket, char *command)
Function to execute the game commands.
Function Documentation
comp_cmd()
int comp_cmd (char * command_type)
Function to compare the command type.
Parameters
char *command_type represent the command type sent by the client.
will compare the command type.
Returns
return 0 if the command type match, and 1 if the command type doesn't match.
Definition at line 13 of file handling_game_command.c.
 {
     if (strcmp(command_type, "Left") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Look") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Broadcast") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Eject") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Take") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Set") == 0) {
         return 0;
     }
     return 1;
 }
Referenced by execute_game_cmd().
comp_cmd_bis()
int comp_cmd_bis (char * command_type)
Function to compare the command type.
Parameters
char *command_type represent the command type sent by the client.
will compare the command type.
Returns
return 0 if the command type match, and 1 if the command type doesn't match.
Definition at line 36 of file handling_game_command.c.
 {
     if (strcmp(command_type, "Forward") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Right") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Fork") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Incantation") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Connect_nbr")) {
         return 0;
     }
     if (strcmp(command_type, "Inventory") == 0) {
         return 0;
     }
     return 1;
 }
Referenced by execute_game_cmd().
execute_game_cmd()
void execute_game_cmd (int cli_socket, char * command)
Function to execute the game commands.
Parameters
int cli_socket represent the client socket.
char *command represent the command sent by the client.
will execute the game commands.
Returns
return noting.
Definition at line 59 of file handling_game_command.c.
 {
     char *buffer = strdup(command);
     char *command_type = strtok(buffer, " ");
     int result = -1;
     cli_socket = cli_socket;
     result = comp_cmd_bis(command_type);
     if (result == 1)
         comp_cmd(command_type);
 }
References comp_cmd(), and comp_cmd_bis().
Referenced by load_cli_and_exec().