PotatZap: Server/include/handle_flags.h File Reference
handle_flags.h File Reference
Contains definitions of the flags handling functions.
Functions
int handle_flags (int argc, char **argv)
Function that allows to handle the flags.
int display_help (void)
Function that displays the help text.
int handle_flags_bis (int ac, char **av, int i, int *flags_present)
Function that allows to handle the flags.
int handle_p (char *av)
Function that handles the port.
int check_av (int i, int ac, char **av)
Function that check the existence of a definition for a flag.
int handle_x (char *av)
Function that check the existence of a definition for x flag.
int handle_y (char *av)
Function that check the existence of a definition for y flag.
int handle_x_y (int ac, int *i, char **av, int *fp)
Function that check the existence of a definition for y and x flags.
int handle_n (int ac, int *i, char **av, int *fp)
Function that check the existence of a definition for n flag.
int handle_c (char *av, int *fp)
Function that check the existence of a definition for c flag.
int handle_f (char *av, int *fp)
Function that check the existence of a definition for f flag.
int n_flag_detection (int ac, int *i, char **av, int *fp)
Function that check the existence of the definition for the n flag.
int handle_n_c_f (int ac, int *i, char **av, int *fp)
Function that check the existence of a definition for n, c and f flags.
int handle_fp (int flags_present)
Function that check the existence of a definition for n, c and f flags.
Detailed Description
Contains definitions of the flags handling functions.
Definition in file handle_flags.h.
Function Documentation
check_av()
int check_av (int i, int ac, char ** av)
Function that check the existence of a definition for a flag.
Parameters
int i index position of the flag
int ac total number of arguments
char **av array that contains all of the arguments of the command line
The function checks if a flag has a definition and if it's definition is valid.
Returns
there is no return value unless if the function found a problem so it return 84
Definition at line 29 of file handle_flags.c.
 {
     if (i + 1 >= ac) {
         fprintf(stderr, "Error: flag %s has no definition\n", av[i]);
         return 84;
     }
     if (av[i + 1][0] == '-') {
         fprintf(stderr, "Error: flag %s has no definition\n", av[i]);
         return 84;
     }
     return 0;
 }
Referenced by handle_flags_bis(), handle_n_c_f(), handle_x_y(), n_flag_detection(), and Test().
display_help()
int display_help (void)
Function that displays the help text.
Parameters
int
display_help is full of printfs that display the usage of the bin
Returns
it exits because it's a int function it doesn't return anything
Definition at line 16 of file handle_flags.c.
 {
     printf("USAGE: ./zappy_server -p port -x width -y height -n name1"
     " name2 ... -c clientsNb -f freq\n");
     printf("\t-p port port number\n");
     printf("\t-x width width of the world\n");
     printf("\t-y height height of the world\n");
     printf("\t-n name1 name2 ... name of the team\n");
     printf("\t-c clientsNb number of authorized clients per team\n");
     printf("\t-f freq reciprocal of time unit for execution of actions\n");
     return 84;
 }
Referenced by handle_flags(), and Test().
handle_c()
int handle_c (char * av, int * fp)
Function that check the existence of a definition for c flag.
Parameters
char *av string that contains the argument
int *fp pointer to the flags_present variable
The function gets the number of clients per team, check the validity of the argument and initialize it in the structure.
Returns
int
Definition at line 39 of file handle_n_c_f.c.
 {
     int nb;
     int i;
     game_t *game = get_game_instance();
     (*fp) |= 1 << 4;
     for (i = 0; av[i]; i++) {
         if (av[i] < '0' || av[i] > '9') {
             fprintf(stderr, "Error: flag -c must be a number\n");
             return 84;
         }
     }
     nb = atoi(av);
     game->player_slots = nb;
     for (int i = 0; i < game->nb_teams; i++)
         game->teams[i]->max_clients = nb;
     return 0;
 }
References game, get_game_instance(), team_s::max_clients, game_s::nb_teams, game_s::player_slots, and game_s::teams.
Referenced by handle_n_c_f(), and Test().
handle_f()
int handle_f (char * av, int * fp)
Function that check the existence of a definition for f flag.
Parameters
char *av string that contains the argument
int *fp pointer to the flags_present variable
The function gets the frequency, check the validity of the argument and initialize it in the structure
Returns
int
Definition at line 59 of file handle_n_c_f.c.
 {
     int nb;
     game_t *game = get_game_instance();
     (*fp) |= 1 << 5;
     for (int i = 0; av[i]; i++) {
         if (av[i] < '0' || av[i] > '9') {
             fprintf(stderr, "Error: flag -f must be a number\n");
             return 84;
         }
     }
     nb = atoi(av);
     game->freq = nb;
     return 0;
 }
References game_s::freq, game, and get_game_instance().
Referenced by handle_n_c_f(), and Test().
handle_flags()
int handle_flags (int argc, char ** argv)
Function that allows to handle the flags.
Parameters
ac number of arguments.
av arguments.
will treat the flags acording to the arguments.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 92 of file handle_flags.c.
 {
     int flags_present = 0;
     int i;
     game_t *game = get_game_instance();
     if (ac == 2 && (strcmp(av[1], "-help") == 0 || strcmp(av[1], "-h") == 0)) {
         display_help();
         return 84;
     }
     for (i = 1; i < ac; i++) {
         if (handle_flags_bis(ac, av, i, &flags_present) == 84)
             return 84;
     }
     if (handle_fp(flags_present) == 84) {
         fprintf(stderr, "Error: missing required flags\n");
         return 84;
     }
     put_c_flag();
     if (!(flags_present & (1 << 5)))
         game->freq = 100;
     return 0;
 }
References display_help(), game_s::freq, game, get_game_instance(), handle_flags_bis(), handle_fp(), and put_c_flag().
Referenced by main(), and Test().
handle_flags_bis()
int handle_flags_bis (int ac, char ** av, int i, int * flags_present)
Function that allows to handle the flags.
Parameters
int ac
char **av
int i
int flags_present
will treat the flags acording to the arguments. (it's the second part of handle_flags)
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 63 of file handle_flags.c.
 {
     if (strcmp(av[i], "-p") == 0) {
         check_av(i, ac, av);
         if (handle_p(av[i + 1]) == 84)
             return 84;
         (*flags_present) |= 1 << 0;
         return 0;
     }
     if (handle_x_y(ac, &i, av, flags_present) == 84) {
         fprintf(stderr, "Error: flag -x or -y has no definition\n");
         return 84;
     }
     if (handle_n_c_f(ac, &i, av, flags_present) == 84) {
         fprintf(stderr, "Error: flag -n, -c or -f has no definition\n");
         return 84;
     }
     return 0;
 }
References check_av(), handle_n_c_f(), handle_p(), and handle_x_y().
Referenced by handle_flags(), and Test().
handle_fp()
int handle_fp (int flags_present)
Function that check the existence of a definition for n, c and f flags.
Parameters
int flags_present reference value of flags present in command line
The function gets the reference value to detect what are the flags present in the command line.
Returns
value 0 if all of the required flags are presents, else return 84.
Definition at line 42 of file handle_flags.c.
 {
     int required_flags = 0x1F;
     if ((flags_present & required_flags) != required_flags) {
             fprintf(stderr, "Error: missing required flags:\n");
         if (!(flags_present & (1 << 0)))
             fprintf(stderr, "-p flag is missing\n");
         if (!(flags_present & (1 << 1)))
             fprintf(stderr, "-x flag is missing\n");
         if (!(flags_present & (1 << 2)))
             fprintf(stderr, "-y flag is missing\n");
         if (!(flags_present & (1 << 3)))
             fprintf(stderr, "-n flag is missing\n");
         if (!(flags_present & (1 << 4)))
             fprintf(stderr, "-c flag is missing\n");
         return 84;
     }
     return 0;
 }
Referenced by handle_flags(), and Test().
handle_n()
int handle_n (int ac, int * i, char ** av, int * fp)
Function that check the existence of a definition for n flag.
Parameters
char *av string that contains the argument
int *fp pointer to the flags_present variable
int ac total number of arguments
int *i index position of the flag
The function gets the teams names
Returns
int
Definition at line 15 of file handle_n_c_f.c.
 {
     game_t *game = get_game_instance();
     int save = *i;
     int k;
     game->nb_teams = 0;
     if (*i + 1 < ac) {
         if (av[*i + 1][0] == '-')
             return 84;
     }
     (*fp) |= 1 << 3;
     while (*i + 1 < ac && av[*i + 1][0] != '-') {
         (*i)++;
         game->nb_teams++;
     }
     game->teams = malloc(sizeof(team_t *) * game->nb_teams);
     for (k = 0; k < game->nb_teams; k++) {
         game->teams[k] = malloc(sizeof(team_t));
         game->teams[k]->name = strdup(av[save + k + 1]);
     }
     return 0;
 }
References game, get_game_instance(), team_s::name, game_s::nb_teams, and game_s::teams.
Referenced by n_flag_detection(), and Test().
handle_n_c_f()
int handle_n_c_f (int ac, int * i, char ** av, int * fp)
Function that check the existence of a definition for n, c and f flags.
Parameters
int ac total number of arguments
int *i index position of the flag
char **av array that contains all of the arguments of the command line
int *fp pointer to the flags_present variable
The function gets the teams names, the nb of clients and frequency
Returns
int unless the function found a problem so it exit 84
Definition at line 92 of file handle_n_c_f.c.
 {
     if (n_flag_detection(ac, i, av, fp) == 84)
         return 84;
     if (strcmp(av[(*i)], "-c") == 0) {
         check_av((*i), ac, av);
         if (handle_c(av[(*i) + 1], fp) == 84) {
             fprintf(stderr, "Error: flag -c GRU\n");
             return 84;
         }
     }
     if (strcmp(av[(*i)], "-f") == 0) {
         check_av((*i), ac, av);
         if (handle_f(av[(*i) + 1], fp) == 84) {
             return 84;
         }
     }
     return 0;
 }
References check_av(), handle_c(), handle_f(), and n_flag_detection().
Referenced by handle_flags_bis(), and Test().
handle_p()
int handle_p (char * av)
Function that handles the port.
Parameters
char *av represents the argument
handle the port, check the validity of the given argument and initialize it in the struct.
Returns
it exits because it's a int function it doesn't return anything
Definition at line 16 of file handle_p_x_y.c.
 {
     int port;
     server_t *server = get_instance();
     for (int i = 0; av[i]; i++)
         if (av[i] < '0' || av[i] > '9') {
             fprintf(stderr, "Error: flag -p must be a number\n");
             return 84;
         }
     port = atoi(av);
     if (port < 1 || port > 65535) {
         fprintf(stderr, "Error: port number must be between 1 and 65535\n");
         return 84;
     }
     server->port = port;
     return 0;
 }
References get_instance(), and server.
Referenced by handle_flags_bis(), and Test().
handle_x()
int handle_x (char * av)
Function that check the existence of a definition for x flag.
Parameters
char *av string that contains the argument
The function gets the width of the world, check the validity of the argument and initialize it in the structure.
Returns
void
Definition at line 35 of file handle_p_x_y.c.
 {
     int x = atoi(av);
     game_t *game = get_game_instance();
     int k;
     for (k = 0; av[k]; k++)
         if ((av[k] < '0' || av[k] > '9')) {
             fprintf(stderr, "Error: flag -x must be a number\n");
             return 84;
         }
     game->width = x;
     return 0;
 }
References game, get_game_instance(), and game_s::width.
Referenced by handle_x_y(), and Test().
handle_x_y()
int handle_x_y (int ac, int * i, char ** av, int * fp)
Function that check the existence of a definition for y and x flags.
Parameters
int ac total number of arguments
int *i index position of the flag
char **av array that contains all of the arguments of the command line
int *fp pointer to the flags_present variable
The function gets the width and height of the world
Returns
int unless the function found a problem so it exit 84
Definition at line 65 of file handle_p_x_y.c.
 {
     if (strcmp(av[(*i)], "-x") == 0) {
         check_av((*i), ac, av);
         if (handle_x(av[(*i) + 1]) == 84)
             return 84;
         (*fp) |= 1 << 1;
     }
     if (strcmp(av[(*i)], "-y") == 0) {
         check_av((*i), ac, av);
         if (handle_y(av[(*i) + 1]) == 84)
             return 84;
         (*fp) |= 1 << 2;
     }
     return 0;
 }
References check_av(), handle_x(), and handle_y().
Referenced by handle_flags_bis(), and Test().
handle_y()
int handle_y (char * av)
Function that check the existence of a definition for y flag.
Parameters
char *av string that contains the argument
The function gets the height of the world, check the validity of the argument and initialize it in the structure.
Returns
void
Definition at line 50 of file handle_p_x_y.c.
 {
     int y = atoi(av);
     game_t *game = get_game_instance();
     int k;
     for (k = 0; av[k]; k++)
         if ((av[k] < '0' || av[k] > '9')) {
             fprintf(stderr, "Error: flag -y has no definition\n");
             return 84;
         }
     game->height = y;
     return 0;
 }
References game, get_game_instance(), and game_s::height.
Referenced by handle_x_y(), and Test().
n_flag_detection()
int n_flag_detection (int ac, int * i, char ** av, int * fp)
Function that check the existence of the definition for the n flag.
Parameters
int ac total number of arguments
int *i index position of the flag
char **av array that contains all of the arguments of the command line
int *fp pointer to the flags_present variable
The function gets the teams names
Returns
int 0 unless the function found a problem so it return 84
Definition at line 76 of file handle_n_c_f.c.
 {
     game_t *game = get_game_instance();
     int status = 0;
     if (strcmp(av[(*i)], "-n") == 0) {
         check_av((*i), ac, av);
         status = handle_n(ac, i, av, fp);
         if (game->nb_teams == 0 || (*i) + 1 > ac || status == 84) {
             fprintf(stderr, "Error: flag -n TEAM1 TEAM2 TEAM3\n");
             return 84;
         }
     }
     return 0;
 }
References check_av(), game, get_game_instance(), handle_n(), and game_s::nb_teams.
Referenced by handle_n_c_f().