PotatZap: Server/src/handle_flags/handle_p_x_y.c File Reference
handle_p_x_y.c File Reference
handle the p, x and y flags
#include "../../include/my.h"
#include "../../include/handle_flags.h"
#include "../../include/get_instance.h"
Functions
int handle_p (char *av)
Function that handles the port.
int handle_x (char *av)
Function that check the existence of a definition for x flag.
int handle_y (char *av)
Function that check the existence of a definition for y flag.
int handle_x_y (int ac, int *i, char **av, int *fp)
Function that check the existence of a definition for y and x flags.
Detailed Description
handle the p, x and y flags
Definition in file handle_p_x_y.c.
Function Documentation
handle_p()
int handle_p (char * av)
Function that handles the port.
Parameters
char *av represents the argument
handle the port, check the validity of the given argument and initialize it in the struct.
Returns
it exits because it's a int function it doesn't return anything
Definition at line 16 of file handle_p_x_y.c.
 {
     int port;
     server_t *server = get_instance();
     for (int i = 0; av[i]; i++)
         if (av[i] < '0' || av[i] > '9') {
             fprintf(stderr, "Error: flag -p must be a number\n");
             return 84;
         }
     port = atoi(av);
     if (port < 1 || port > 65535) {
         fprintf(stderr, "Error: port number must be between 1 and 65535\n");
         return 84;
     }
     server->port = port;
     return 0;
 }
References get_instance(), and server.
Referenced by handle_flags_bis(), and Test().
handle_x()
int handle_x (char * av)
Function that check the existence of a definition for x flag.
Parameters
char *av string that contains the argument
The function gets the width of the world, check the validity of the argument and initialize it in the structure.
Returns
void
Definition at line 35 of file handle_p_x_y.c.
 {
     int x = atoi(av);
     game_t *game = get_game_instance();
     int k;
     for (k = 0; av[k]; k++)
         if ((av[k] < '0' || av[k] > '9')) {
             fprintf(stderr, "Error: flag -x must be a number\n");
             return 84;
         }
     game->width = x;
     return 0;
 }
References game, get_game_instance(), and game_s::width.
Referenced by handle_x_y(), and Test().
handle_x_y()
int handle_x_y (int ac, int * i, char ** av, int * fp)
Function that check the existence of a definition for y and x flags.
Parameters
int ac total number of arguments
int *i index position of the flag
char **av array that contains all of the arguments of the command line
int *fp pointer to the flags_present variable
The function gets the width and height of the world
Returns
int unless the function found a problem so it exit 84
Definition at line 65 of file handle_p_x_y.c.
 {
     if (strcmp(av[(*i)], "-x") == 0) {
         check_av((*i), ac, av);
         if (handle_x(av[(*i) + 1]) == 84)
             return 84;
         (*fp) |= 1 << 1;
     }
     if (strcmp(av[(*i)], "-y") == 0) {
         check_av((*i), ac, av);
         if (handle_y(av[(*i) + 1]) == 84)
             return 84;
         (*fp) |= 1 << 2;
     }
     return 0;
 }
References check_av(), handle_x(), and handle_y().
Referenced by handle_flags_bis(), and Test().
handle_y()
int handle_y (char * av)
Function that check the existence of a definition for y flag.
Parameters
char *av string that contains the argument
The function gets the height of the world, check the validity of the argument and initialize it in the structure.
Returns
void
Definition at line 50 of file handle_p_x_y.c.
 {
     int y = atoi(av);
     game_t *game = get_game_instance();
     int k;
     for (k = 0; av[k]; k++)
         if ((av[k] < '0' || av[k] > '9')) {
             fprintf(stderr, "Error: flag -y has no definition\n");
             return 84;
         }
     game->height = y;
     return 0;
 }
References game, get_game_instance(), and game_s::height.
Referenced by handle_x_y(), and Test().