PotatZap: Server/src/handle_flags/handle_flags.c File Reference
handle_flags.c File Reference
functions to handle the flags, hub and error handling part
#include "../../include/my.h"
#include "../../include/handle_flags.h"
#include "../../include/get_instance.h"
Functions
int display_help (void)
Function that displays the help text.
int check_av (int i, int ac, char **av)
Function that check the existence of a definition for a flag.
int handle_fp (int flags_present)
Function that check the existence of a definition for n, c and f flags.
int handle_flags_bis (int ac, char **av, int i, int *flags_present)
Function that allows to handle the flags.
static int put_c_flag (void)
int handle_flags (int ac, char **av)
Function that allows to handle the flags.
Detailed Description
functions to handle the flags, hub and error handling part
Definition in file handle_flags.c.
Function Documentation
check_av()
int check_av (int i, int ac, char ** av)
Function that check the existence of a definition for a flag.
Parameters
int i index position of the flag
int ac total number of arguments
char **av array that contains all of the arguments of the command line
The function checks if a flag has a definition and if it's definition is valid.
Returns
there is no return value unless if the function found a problem so it return 84
Definition at line 29 of file handle_flags.c.
 {
     if (i + 1 >= ac) {
         fprintf(stderr, "Error: flag %s has no definition\n", av[i]);
         return 84;
     }
     if (av[i + 1][0] == '-') {
         fprintf(stderr, "Error: flag %s has no definition\n", av[i]);
         return 84;
     }
     return 0;
 }
Referenced by handle_flags_bis(), handle_n_c_f(), handle_x_y(), n_flag_detection(), and Test().
display_help()
int display_help (void)
Function that displays the help text.
Parameters
int
display_help is full of printfs that display the usage of the bin
Returns
it exits because it's a int function it doesn't return anything
Definition at line 16 of file handle_flags.c.
 {
     printf("USAGE: ./zappy_server -p port -x width -y height -n name1"
     " name2 ... -c clientsNb -f freq\n");
     printf("\t-p port port number\n");
     printf("\t-x width width of the world\n");
     printf("\t-y height height of the world\n");
     printf("\t-n name1 name2 ... name of the team\n");
     printf("\t-c clientsNb number of authorized clients per team\n");
     printf("\t-f freq reciprocal of time unit for execution of actions\n");
     return 84;
 }
Referenced by handle_flags(), and Test().
handle_flags()
int handle_flags (int argc, char ** argv)
Function that allows to handle the flags.
Parameters
ac number of arguments.
av arguments.
will treat the flags acording to the arguments.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 92 of file handle_flags.c.
 {
     int flags_present = 0;
     int i;
     game_t *game = get_game_instance();
     if (ac == 2 && (strcmp(av[1], "-help") == 0 || strcmp(av[1], "-h") == 0)) {
         display_help();
         return 84;
     }
     for (i = 1; i < ac; i++) {
         if (handle_flags_bis(ac, av, i, &flags_present) == 84)
             return 84;
     }
     if (handle_fp(flags_present) == 84) {
         fprintf(stderr, "Error: missing required flags\n");
         return 84;
     }
     put_c_flag();
     if (!(flags_present & (1 << 5)))
         game->freq = 100;
     return 0;
 }
References display_help(), game_s::freq, game, get_game_instance(), handle_flags_bis(), handle_fp(), and put_c_flag().
Referenced by main(), and Test().
handle_flags_bis()
int handle_flags_bis (int ac, char ** av, int i, int * flags_present)
Function that allows to handle the flags.
Parameters
int ac
char **av
int i
int flags_present
will treat the flags acording to the arguments. (it's the second part of handle_flags)
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 63 of file handle_flags.c.
 {
     if (strcmp(av[i], "-p") == 0) {
         check_av(i, ac, av);
         if (handle_p(av[i + 1]) == 84)
             return 84;
         (*flags_present) |= 1 << 0;
         return 0;
     }
     if (handle_x_y(ac, &i, av, flags_present) == 84) {
         fprintf(stderr, "Error: flag -x or -y has no definition\n");
         return 84;
     }
     if (handle_n_c_f(ac, &i, av, flags_present) == 84) {
         fprintf(stderr, "Error: flag -n, -c or -f has no definition\n");
         return 84;
     }
     return 0;
 }
References check_av(), handle_n_c_f(), handle_p(), and handle_x_y().
Referenced by handle_flags(), and Test().
handle_fp()
int handle_fp (int flags_present)
Function that check the existence of a definition for n, c and f flags.
Parameters
int flags_present reference value of flags present in command line
The function gets the reference value to detect what are the flags present in the command line.
Returns
value 0 if all of the required flags are presents, else return 84.
Definition at line 42 of file handle_flags.c.
 {
     int required_flags = 0x1F;
     if ((flags_present & required_flags) != required_flags) {
             fprintf(stderr, "Error: missing required flags:\n");
         if (!(flags_present & (1 << 0)))
             fprintf(stderr, "-p flag is missing\n");
         if (!(flags_present & (1 << 1)))
             fprintf(stderr, "-x flag is missing\n");
         if (!(flags_present & (1 << 2)))
             fprintf(stderr, "-y flag is missing\n");
         if (!(flags_present & (1 << 3)))
             fprintf(stderr, "-n flag is missing\n");
         if (!(flags_present & (1 << 4)))
             fprintf(stderr, "-c flag is missing\n");
         return 84;
     }
     return 0;
 }
Referenced by handle_flags(), and Test().
put_c_flag()
static int put_c_flag (void) static
Definition at line 83 of file handle_flags.c.
 {
     game_t *game = get_game_instance();
     for (int i = 0; i < game->nb_teams; i++)
         game->teams[i]->max_clients = game->player_slots;
     return 0;
 }
References game, get_game_instance(), team_s::max_clients, game_s::nb_teams, game_s::player_slots, and game_s::teams.
Referenced by handle_flags().