PotatZap: Server/src/server/handling_login_phase.c File Reference
handling_login_phase.c File Reference
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
int handle_team_full (client_t *cli, team_t *team, char *team_name)
int detect_team_validity (char *team_name, client_t *cli)
Function to check if the team name is valid or not.
void handle_cli_login (client_t *cli, char *command)
Function to handle the client login phase.
Function Documentation
detect_team_validity()
int detect_team_validity (char * team_name, client_t * cli)
Function to check if the team name is valid or not.
Parameters
char *team_name represent the team name sent by the client.
client_t *cli represent the client entity that contains client informations.
will check if the team name exists or not and so change connected status of the client.
Returns
return 0 if there is no error, and 84 if there is an error.
Definition at line 36 of file handling_login_phase.c.
 {
     game_t *game = get_game_instance();
     for (int i = 0; i < game->nb_teams; i++) {
         if (strcmp(game->teams[i]->name, team_name) == 0) {
             cli->status = true;
             cli->team = strdup(team_name);
             return handle_team_full(cli, game->teams[i], team_name);
         }
     }
     return 84;
 }
References game, get_game_instance(), handle_team_full(), team_s::name, game_s::nb_teams, and game_s::teams.
Referenced by handle_cli_login().
handle_cli_login()
void handle_cli_login (client_t * cli, char * command)
Function to handle the client login phase.
Parameters
client_t *cli represent the client entity that contains client informations.
char *command represent the team name sent by the client.
will check if the team name is valid and if the team is full or not.
Returns
return noting.
Definition at line 50 of file handling_login_phase.c.
 {
     char *msg = "Wrong team name, please try again\r\n";
     if (cli->status == false && detect_team_validity(command, cli) == 0)
         return;
     if (cli->status == false && detect_team_validity(command, cli) == 84) {
         write(cli->socket, msg, strlen(msg));
         return;
     }
 }
References detect_team_validity().
Referenced by load_cli_and_exec().
handle_team_full()
int handle_team_full (client_t * cli, team_t * team, char * team_name)
Definition at line 13 of file handling_login_phase.c.
 {
     game_t *game = get_game_instance();
     char slots[1024];
     char coordinates[1024];
     int length;
     if (team->max_clients < 1) {
         add_to_waiting_list(cli->socket, team_name);
         write(cli->socket, "This team is full, please wait\r\n",
             strlen("This team is full, please wait\r\n"));
         return 0;
     } else {
         team->max_clients -= 1;
         length = snprintf(slots, sizeof(slots), "%d\r\n", team->max_clients);
         write(cli->socket, slots, length);
         length = snprintf(coordinates, sizeof(coordinates),
             "%d %d\r\n", game->width, game->height);
         write(cli->socket, coordinates, length);
         return 0;
     }
 }
References add_to_waiting_list(), game, get_game_instance(), game_s::height, team_s::max_clients, team, and game_s::width.
Referenced by detect_team_validity().