PotatZap: Server/src/handle_flags/handle_n_c_f.c File Reference
handle_n_c_f.c File Reference
handle the n, c and f flags
#include "../../include/my.h"
#include "../../include/handle_flags.h"
#include "../../include/get_instance.h"
Functions
int handle_n (int ac, int *i, char **av, int *fp)
Function that check the existence of a definition for n flag.
int handle_c (char *av, int *fp)
Function that check the existence of a definition for c flag.
int handle_f (char *av, int *fp)
Function that check the existence of a definition for f flag.
int n_flag_detection (int ac, int *i, char **av, int *fp)
Function that check the existence of the definition for the n flag.
int handle_n_c_f (int ac, int *i, char **av, int *fp)
Function that check the existence of a definition for n, c and f flags.
Detailed Description
handle the n, c and f flags
Definition in file handle_n_c_f.c.
Function Documentation
handle_c()
int handle_c (char * av, int * fp)
Function that check the existence of a definition for c flag.
Parameters
char *av string that contains the argument
int *fp pointer to the flags_present variable
The function gets the number of clients per team, check the validity of the argument and initialize it in the structure.
Returns
int
Definition at line 39 of file handle_n_c_f.c.
 {
     int nb;
     int i;
     game_t *game = get_game_instance();
     (*fp) |= 1 << 4;
     for (i = 0; av[i]; i++) {
         if (av[i] < '0' || av[i] > '9') {
             fprintf(stderr, "Error: flag -c must be a number\n");
             return 84;
         }
     }
     nb = atoi(av);
     game->player_slots = nb;
     for (int i = 0; i < game->nb_teams; i++)
         game->teams[i]->max_clients = nb;
     return 0;
 }
References game, get_game_instance(), team_s::max_clients, game_s::nb_teams, game_s::player_slots, and game_s::teams.
Referenced by handle_n_c_f(), and Test().
handle_f()
int handle_f (char * av, int * fp)
Function that check the existence of a definition for f flag.
Parameters
char *av string that contains the argument
int *fp pointer to the flags_present variable
The function gets the frequency, check the validity of the argument and initialize it in the structure
Returns
int
Definition at line 59 of file handle_n_c_f.c.
 {
     int nb;
     game_t *game = get_game_instance();
     (*fp) |= 1 << 5;
     for (int i = 0; av[i]; i++) {
         if (av[i] < '0' || av[i] > '9') {
             fprintf(stderr, "Error: flag -f must be a number\n");
             return 84;
         }
     }
     nb = atoi(av);
     game->freq = nb;
     return 0;
 }
References game_s::freq, game, and get_game_instance().
Referenced by handle_n_c_f(), and Test().
handle_n()
int handle_n (int ac, int * i, char ** av, int * fp)
Function that check the existence of a definition for n flag.
Parameters
char *av string that contains the argument
int *fp pointer to the flags_present variable
int ac total number of arguments
int *i index position of the flag
The function gets the teams names
Returns
int
Definition at line 15 of file handle_n_c_f.c.
 {
     game_t *game = get_game_instance();
     int save = *i;
     int k;
     game->nb_teams = 0;
     if (*i + 1 < ac) {
         if (av[*i + 1][0] == '-')
             return 84;
     }
     (*fp) |= 1 << 3;
     while (*i + 1 < ac && av[*i + 1][0] != '-') {
         (*i)++;
         game->nb_teams++;
     }
     game->teams = malloc(sizeof(team_t *) * game->nb_teams);
     for (k = 0; k < game->nb_teams; k++) {
         game->teams[k] = malloc(sizeof(team_t));
         game->teams[k]->name = strdup(av[save + k + 1]);
     }
     return 0;
 }
References game, get_game_instance(), team_s::name, game_s::nb_teams, and game_s::teams.
Referenced by n_flag_detection(), and Test().
handle_n_c_f()
int handle_n_c_f (int ac, int * i, char ** av, int * fp)
Function that check the existence of a definition for n, c and f flags.
Parameters
int ac total number of arguments
int *i index position of the flag
char **av array that contains all of the arguments of the command line
int *fp pointer to the flags_present variable
The function gets the teams names, the nb of clients and frequency
Returns
int unless the function found a problem so it exit 84
Definition at line 92 of file handle_n_c_f.c.
 {
     if (n_flag_detection(ac, i, av, fp) == 84)
         return 84;
     if (strcmp(av[(*i)], "-c") == 0) {
         check_av((*i), ac, av);
         if (handle_c(av[(*i) + 1], fp) == 84) {
             fprintf(stderr, "Error: flag -c GRU\n");
             return 84;
         }
     }
     if (strcmp(av[(*i)], "-f") == 0) {
         check_av((*i), ac, av);
         if (handle_f(av[(*i) + 1], fp) == 84) {
             return 84;
         }
     }
     return 0;
 }
References check_av(), handle_c(), handle_f(), and n_flag_detection().
Referenced by handle_flags_bis(), and Test().
n_flag_detection()
int n_flag_detection (int ac, int * i, char ** av, int * fp)
Function that check the existence of the definition for the n flag.
Parameters
int ac total number of arguments
int *i index position of the flag
char **av array that contains all of the arguments of the command line
int *fp pointer to the flags_present variable
The function gets the teams names
Returns
int 0 unless the function found a problem so it return 84
Definition at line 76 of file handle_n_c_f.c.
 {
     game_t *game = get_game_instance();
     int status = 0;
     if (strcmp(av[(*i)], "-n") == 0) {
         check_av((*i), ac, av);
         status = handle_n(ac, i, av, fp);
         if (game->nb_teams == 0 || (*i) + 1 > ac || status == 84) {
             fprintf(stderr, "Error: flag -n TEAM1 TEAM2 TEAM3\n");
             return 84;
         }
     }
     return 0;
 }
References check_av(), game, get_game_instance(), handle_n(), and game_s::nb_teams.
Referenced by handle_n_c_f().