PotatZap: Server/src/server/init_server.c File Reference
init_server.c File Reference
init server
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
#include "../../include/my.h"
Functions
int init_server_listen (void)
Function that init the listening of the server.
int init_server_launch (void)
Function that init the launch of the server.
int init_socket (void)
Function that init the socket of the server.
int init_server_bis (void)
Function that init the construction process of the server.
int init_server (void)
Function that init the server struct parameters.
Detailed Description
init server
Definition in file init_server.c.
Function Documentation
init_server()
int init_server (void)
Function that init the server struct parameters.
Parameters
void no parameters are required.
will set the components of the server structure to their default values, init the different linked list and will call the init_server_bis function to init the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 78 of file init_server.c.
 {
     server_t *server = get_instance();
     if (server == NULL) {
         fprintf(stderr, "Error: server non existant\n");
         return 84;
     }
     server->maxfd = 0;
     server->nb_players = 0;
     server->clients = NULL;
     TAILQ_INIT(&server->waiting_list);
     TAILQ_INIT(&server->commands);
     if (init_server_bis() == 84) {
         fprintf(stderr, "Error: server init failed\n");
         return 84;
     }
     return 0;
 }
References get_instance(), init_server_bis(), and server.
Referenced by main(), and Test().
init_server_bis()
int init_server_bis (void)
Function that init the construction process of the server.
Parameters
void no parameters are required.
will call all of the necessary functions to create and launch the server. Such as fill the sockeaddr structure
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 60 of file init_server.c.
 {
     server_t *server = get_instance();
     if (init_socket() == 84) {
         fprintf(stderr, "Error: socket creation failed\n");
         return 84;
     }
     server->sockaddr.sin_family = AF_INET;
     server->sockaddr.sin_addr.s_addr = INADDR_ANY;
     server->sockaddr.sin_port = htons(server->port);
     if (init_server_launch() == 84) {
         fprintf(stderr, "Error: server launch failed\n");
         return 84;
     }
     return 0;
 }
References get_instance(), init_server_launch(), init_socket(), and server.
Referenced by init_server(), and Test().
init_server_launch()
int init_server_launch (void)
Function that init the launch of the server.
Parameters
void no parameters are required.
will bind the server to the address and port, set the socket to non blocking and will call the init_server_listen function to listen to the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 28 of file init_server.c.
 {
     server_t *server = get_instance();
     if (bind(server->socket, (struct sockaddr *)&server->sockaddr,
         sizeof(server->sockaddr)) < 0) {
         perror("bind");
         return 84;
     }
     if (init_server_listen() == 84)
         return 84;
     return 0;
 }
References get_instance(), init_server_listen(), and server.
Referenced by init_server_bis(), and Test().
init_server_listen()
int init_server_listen (void)
Function that init the listening of the server.
Parameters
void no parameters are required.
will listen to the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 17 of file init_server.c.
 {
     server_t *server = get_instance();
     if (listen(server->socket, 3) < 0) {
         perror("listen");
         return 84;
     }
     return 0;
 }
References get_instance(), and server.
Referenced by init_server_launch(), and Test().
init_socket()
int init_socket (void)
Function that init the socket of the server.
Parameters
void no parameters are required.
will create the socket of the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 42 of file init_server.c.
 {
     server_t *server = get_instance();
     int opt = 1;
     server->socket = socket(AF_INET, SOCK_STREAM, 0);
     if (server->socket == -1) {
         perror("socket");
         return 84;
     }
     if (setsockopt(server->socket, SOL_SOCKET,
         SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt)) < 0) {
         perror("Setsockopt failed");
         return 84;
     }
     return 0;
 }
References get_instance(), and server.
Referenced by init_server_bis(), and Test().