PotatZap: Server/include/my.h File Reference
my.h File Reference
defines the prototypes of the functions used in the project as well as the includes of the libs needed
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/queue.h>
#include <sys/select.h>
#include <sys/types.h>
#include "struct_map.h"
#include <errno.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <time.h>
#include <linux/time.h>
Functions
int add_func (int a, int b)
void second_init_map (map_t *map, int x, int y, int width)
void init_map (map_t *map, int width, int height)
map_t * initialize_map (int width, int height)
void display (struct map_s *map)
void display_suite (items_t *item)
Detailed Description
defines the prototypes of the functions used in the project as well as the includes of the libs needed
defines data structures used in the project for the map
defines the data structures used in the project for the client/player, such as inventory, position, etc.
Definition in file my.h.
Function Documentation
add_func()
int add_func (int a, int b)
display()
void display (struct map_s * map)
Definition at line 23 of file init_map.c.
 {
     items_t *item;
     for (int x = 0; x < map->width; x++) {
         for (int y = 0; y < map->height; y++) {
             printf("Tile at (%d, %d):\n", x, y);
             item = map->tiles[x + y * map->width]->items;
             display_suite(item);
         }
     }
 }
References display_suite(), map_s::height, map_s::tiles, and map_s::width.
Referenced by initialize_map().
display_suite()
void display_suite (items_t * item)
Definition at line 15 of file init_map.c.
 {
     while (item) {
         printf("Item: %s\n", item->type == FOOD ? "FOOD" : "RESOURCE");
         item = item->next;
     }
 }
References FOOD.
Referenced by display().
init_map()
void init_map (map_t * map, int width, int height)
Definition at line 49 of file init_map.c.
 {
     int x;
     int y;
     for (x = 0; x < width; x++) {
         for (y = 0; y < height; y++) {
             map->tiles[x + y * width] = malloc(sizeof(tile_t));
             second_init_map(map, x, y, width);
             map->tiles[x + y * width]->x = x;
             map->tiles[x + y * width]->y = y;
             map->tiles[x + y * width]->items = NULL;
         }
     }
 }
References second_init_map().
Referenced by initialize_map(), and Test().
initialize_map()
map_t* initialize_map (int width, int height)
Definition at line 65 of file init_map.c.
 {
     map_t *map = malloc(sizeof(map_t));
     if (!map)
         return NULL;
     map->width = width;
     map->height = height;
     map->tiles = malloc(width * height * sizeof(tile_t *));
     if (!map->tiles) {
         free(map);
         return NULL;
     }
     init_map(map, width, height);
     map->display = &display;
     return map;
 }
References display(), and init_map().
Referenced by Test().
second_init_map()
void second_init_map (map_t * map, int x, int y, int width)
Definition at line 36 of file init_map.c.
 {
     int i;
     if (!map->tiles[x + y * width]) {
         for (i = 0; i < x + y * width; i++)
             free(map->tiles[i]);
         free(map->tiles);
         free(map);
         return;
     }
 }
Referenced by init_map().