PotatZap: zappy_ai Namespace Reference
zappy_ai Namespace Reference
Classes
class Player
Functions
def split_by_commas (input_string)
def find_keyword_in_list (strings, keyword)
def count_words_at_index (strings, index)
def remove_element (strings, index, element)
def send_and_remove (client_socket, player, index, element)
def going_forward (client_socket, player)
def turning_right (client_socket, player)
def turning_left (client_socket, player)
def looking (client_socket, player)
def check_stones (player, index)
def check_level_two (player, client_socket)
def check_level_three (player, client_socket)
def check_level_four (player, client_socket)
def can_evolve (client_socket, player)
def received_look (player, data_rec)
def reduce_max (player)
def inventory (player, data_rec)
def command_received (player, data_rec)
def moving_level (client_socket, player)
def go_to_need (client_socket, player)
def moving_player (client_socket, player)
def incant_nb (player)
def command_send (client_socket, player)
def netcat_client (host, port, name)
Variables
list required_args = ['-p', '--port', '-n', '--name']
list missing_args = [arg for arg in required_args if arg not in sys.argv]
parser = argparse.ArgumentParser(add_help=False)
type
int
required
True
help
str
default
action
args = parser.parse_args()
Detailed Description
@file zappy_ai.py
@brief File containing every functions related to ai.
Function Documentation
can_evolve()
def zappy_ai.can_evolve (client_socket, player)
@brief Checks if the conditions are met to evolve, if so set player.incanting to true and adds the request to evolve to player.queue.
@param client_socket Socket where to send the string.
@param player Player class containing queue and incanting.
@return True if the player can evolve, else false.
Definition at line 330 of file zappy_ai.py.
 def can_evolve(client_socket, player):
     """
     @brief Checks if the conditions are met to evolve, if so set player.incanting to true and adds the request to evolve to player.queue.
     @param client_socket Socket where to send the string.
     @param player Player class containing queue and incanting.
     @return True if the player can evolve, else false.
     """
     if player.incanting == True or player.need_to_go != None:
         return False
     if player.view != [] :
         if player.level == 1:
             if player.view[0].count("player") >= 2:
                 return False
             if check_stones(player, 0) == "linemate":
                 data_send = "Incantation\n"
                 print(f"Sending : {data_send}", end="")
                 client_socket.send(data_send.encode())
                 player.queue.append(data_send)
                 player.incanting = True
                 return True
             else :
                 return False
         elif player.level == 2 :
             if player.view[0].count("player") >= 2:
                 return False
             if player.wants_incanting == True :
                 return True
             if check_level_two(player, client_socket) :
                 player.wants_incanting = True
                 player.nb_r = 1
                 return True
             else :
                 return False
         elif player.level == 3 :
             if player.view[0].count("player") >= 2:
                 return False
             if player.wants_incanting == True :
                 return True
             if check_level_three(player, client_socket) :
                 player.wants_incanting = True
                 player.nb_r = 1
                 return True
             else :
                 return False
         elif player.level == 4 :
             if player.view[0].count("player") >= 2:
                 return False
             if player.wants_incanting == True :
                 return True
             if check_level_four(player, client_socket) :
                 player.wants_incanting = True
                 player.nb_r = 1
                 return True
             else :
                 return False
         else :
             return False
     else :
         return False
References check_level_four(), check_level_three(), check_level_two(), and check_stones().
Referenced by command_send(), and test_zappy_ai.TestZappyAI.test_can_evolve().
check_level_four()
def zappy_ai.check_level_four (player, client_socket)
Definition at line 279 of file zappy_ai.py.
 def check_level_four(player, client_socket) :
     l = player.view[0].count("linemate")
     if (l + player.linemate) < 1:
         return False
     d = player.view[0].count("deraumere")
     if (d + player.deraumere) < 1:
         return False
     s = player.view[0].count("sibur")
     if (s + player.sibur) < 2 :
         return False
     p = player.view[0].count("phiras")
     if (p + player.phiras) < 1:
         return False
     if player.starve == None:
         data_send = "Inventory\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         return False
     elif player.starve < 15 :
         player.starve = None
         return False
     if (l < 1) :
         player.linemate -= 1
         data_send = "Set linemate\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         # l += 1
     if (d < 1) :
         player.deraumere -= 1
         data_send = "Set deraumere\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
     while (s < 2) :
         player.sibur -= 1
         data_send = "Set sibur\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         s += 1
     if (p < 1) :
         player.phiras -= 1
         data_send = "Set phiras\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         # p += 1
     return True
Referenced by can_evolve().
check_level_three()
def zappy_ai.check_level_three (player, client_socket)
Definition at line 236 of file zappy_ai.py.
 def check_level_three(player, client_socket) :
     l = player.view[0].count("linemate")
     if (l + player.linemate) < 2:
         return False
     s = player.view[0].count("sibur")
     if (s + player.sibur) < 1 :
         return False
     p = player.view[0].count("phiras")
     if (p + player.phiras) < 2:
         return False
     if player.starve == None:
         data_send = "Inventory\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         return False
     elif player.starve < 12 :
         player.starve = None
         return False
     while (l < 2) :
         player.linemate -= 1
         data_send = "Set linemate\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         l += 1
     if (s < 1) :
         player.sibur -= 1
         data_send = "Set sibur\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
     while (p < 2) :
         player.phiras -= 1
         data_send = "Set phiras\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         p += 1
     return True
Referenced by can_evolve().
check_level_two()
def zappy_ai.check_level_two (player, client_socket)
Definition at line 198 of file zappy_ai.py.
 def check_level_two(player, client_socket) :
     if (not 0 in find_keyword_in_list(player.view, "linemate")) and player.linemate == 0 :
         return False
     if (not 0 in find_keyword_in_list(player.view, "deraumere")) and player.deraumere == 0 :
         return False
     if (not 0 in find_keyword_in_list(player.view, "sibur")) and player.sibur == 0 :
         return False
     if player.starve == None:
         data_send = "Inventory\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
         return False
     elif player.starve < 8 :
         player.starve = None
         return False
     if (not 0 in find_keyword_in_list(player.view, "sibur")) :
         player.sibur -= 1
         data_send = "Set sibur\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
     if (not 0 in find_keyword_in_list(player.view, "deraumere")) :
         player.deraumere -= 1
         data_send = "Set deraumere\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
     if (not 0 in find_keyword_in_list(player.view, "linemate")) :
         player.linemate -= 1
         data_send = "Set linemate\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
     return True
References find_keyword_in_list().
Referenced by can_evolve().
check_stones()
def zappy_ai.check_stones (player, index)
@brief Checks if there is a stone still needed by the player at an index of player.view.
@param player Player class containing view and all stone related informations.
@param index Index to look at for stones still needed.
@return Returns the name of the stone if there is one needed, else return None.
Definition at line 174 of file zappy_ai.py.
 def check_stones(player, index):
     """
     @brief Checks if there is a stone still needed by the player at an index of player.view.
     @param player Player class containing view and all stone related informations.
     @param index Index to look at for stones still needed.
     @return Returns the name of the stone if there is one needed, else return None.
     """
     if 0 <= index < len(player.view):
         items = player.view[index].split()
         for item in items:
             if item == "linemate" and player.linemate < player.max_linemate:
                 return "linemate"
             elif item == "deraumere" and player.deraumere < player.max_deraumere:
                 return "deraumere"
             elif item == "sibur" and player.sibur < player.max_sibur:
                 return "sibur"
             elif item == "mendiane" and player.mendiane < player.max_mendiane:
                 return "mendiane"
             elif item == "phiras" and player.phiras < player.max_phiras:
                 return "phiras"
             elif item == "thystame" and player.thystame < player.max_thystame:
                 return "thystame"
     return None
Referenced by can_evolve(), command_send(), moving_level(), and test_zappy_ai.TestZappyAI.test_check_stones().
command_received()
def zappy_ai.command_received (player, data_rec)
@brief Checks the received data to know what to do.
@param player Player class containing queue.
@param data_rec String containing ko or a potential instruction.
Definition at line 422 of file zappy_ai.py.
 def command_received(player, data_rec):
     """
     @brief Checks the received data to know what to do.
     @param player Player class containing queue.
     @param data_rec String containing ko or a potential instruction.
     """
     print(f"Received: {data_rec.decode()}", end="")
     if data_rec.decode() == "Elevation underway\n":
         return
     if "message" in data_rec.decode() :
         words = data_rec.decode().replace('"', '').replace(',', '').split()
         if len(words) > 3 and words[0] == "message" and words[2] == "Level" :
             player_num = words[1]
             player_level = words[3]
             if int(player_level) == int(player.level):
                 if words[4] == "c" :
                     player.nb_r += 1
                     if incant_nb(player) and (player.need_to_go != 0 and player.wants_incanting == False) :
                         player.need_to_go = None
                         player.nb_r = 0
                         return
                 elif words[4] == "r" :
                     player.need_to_go = int(player_num)
                 if player.nb_r == 0 :
                     player.nb_r = 1
         return
     if data_rec.decode() == f"Current level: {player.level + 1}\n" :
         player.level += 1
         player.view = []
         player.look = False
         player.nb_r = 0
         player.wants_incanting = False
         player.incanting = False
         player.need_to_go = None
         reduce_max(player)
         if len(player.queue) > 0 :
             if player.queue[0] == "Incantation\n":
                 player.queue.pop(0)
         print(f"Player got level : {player.level}", file=sys.stderr)
         return
     if len(player.queue) > 0 :
         if "Inventory" in player.queue[0] :
             inventory(player, data_rec.decode())
         if "Broadcast" in player.queue[0] :
             player.queue.pop(0)
             return
         if "Take" in player.queue[0]:
             item = player.queue[0].split()[1]
             if hasattr(player, item):
                 setattr(player, item, getattr(player, item) + 1)
             player.queue.pop(0)
             return
         if player.look == True and player.view == [] and player.queue[0] == "Look\n":
             received_look(player, data_rec)
         if player.queue[0] == "Incantation\n" and data_rec.decode() == "ko\n":
             player.view = []
             player.look = False
             player.nb_r = 0
             player.wants_incanting = False
             player.incanting = False
             player.need_to_go = None
         player.queue.pop(0)
References incant_nb(), int, inventory(), received_look(), and reduce_max().
Referenced by netcat_client(), and test_zappy_ai.TestZappyAI.test_command_received().
command_send()
def zappy_ai.command_send (client_socket, player)
@brief Checks informations in player class to know what command to do.
@param client_socket Socket where to potentially send information.
@param player Player class.
Definition at line 653 of file zappy_ai.py.
 def command_send(client_socket, player):
     """
     @brief Checks informations in player class to know what command to do.
     @param client_socket Socket where to potentially send information.
     @param player Player class.
     """
     if player.wants_incanting == True :
         if len(player.queue) >= 1 :
             return
         else :
             if incant_nb(player) :
                 data_send = "Incantation\n"
                 print(f"Sending : {data_send}", end="")
                 client_socket.send(data_send.encode())
                 player.queue.append(data_send)
                 player.incanting = True
                 player.nb_r = 0
                 player.wants_incanting = False
                 return #evolve
             data_send = f"Broadcast \"Level {player.level} r\"\n"
             print(f"Sending : {data_send}", end="")
             client_socket.send(data_send.encode())
             player.queue.append(data_send)
     if player.look == False :
         if len(player.queue) > 0 :
             return
         looking(client_socket, player)
     if can_evolve(client_socket, player) or player.incanting or player.wants_incanting :
         return
     if player.look == True and player.view != [] :
         if count_words_at_index(player.view, 0) > 0 and 0 in find_keyword_in_list(player.view, "food") :
             send_and_remove(client_socket, player, 0, "food")
         elif count_words_at_index(player.view, 0) > 0 :
             stone = check_stones(player, 0)
             if stone != None and not 0 in find_keyword_in_list(player.view, "player player") :
                 send_and_remove(client_socket, player, 0, stone)
             else :
                 moving_player(client_socket, player)
         else :
             moving_player(client_socket, player)
References can_evolve(), check_stones(), count_words_at_index(), find_keyword_in_list(), incant_nb(), looking(), moving_player(), and send_and_remove().
Referenced by netcat_client(), and test_zappy_ai.TestZappyAI.test_command_send().
count_words_at_index()
def zappy_ai.count_words_at_index (strings, index)
@brief Counts the number of words in a list at a certain index (excluding the words "egg" and "player").
@param strings List of strings.
@param index Index where to count in the list.
@return Number of words in the list at the given index.
Definition at line 87 of file zappy_ai.py.
 def count_words_at_index(strings, index):
     """
     @brief Counts the number of words in a list at a certain index (excluding the words "egg" and "player").
     @param strings List of strings.
     @param index Index where to count in the list.
     @return Number of words in the list at the given index.
     """
     if 0 <= index < len(strings):
         words = strings[index].split()
         words = [word for word in words if word != "egg" and word != "player"]
         return len(words)
     else:
         return 0
Referenced by command_send(), moving_level(), and test_zappy_ai.TestZappyAI.test_count_words_at_index().
find_keyword_in_list()
def zappy_ai.find_keyword_in_list (strings, keyword)
@brief Finds the index of every keyword in the list.
@param strings List of words.
@param keyword Word to find in the list.
@return A list of every indexes where the keyword is in the list.
Definition at line 74 of file zappy_ai.py.
 def find_keyword_in_list(strings, keyword):
     """
     @brief Finds the index of every keyword in the list.
     @param strings List of words.
     @param keyword Word to find in the list.
     @return A list of every indexes where the keyword is in the list.
     """
     indices = []
     for index, string in enumerate(strings):
         if keyword in string:
             indices.append(index)
     return indices
Referenced by check_level_two(), command_send(), moving_level(), and test_zappy_ai.TestZappyAI.test_find_keyword_in_list().
go_to_need()
def zappy_ai.go_to_need (client_socket, player)
Definition at line 589 of file zappy_ai.py.
 def go_to_need(client_socket, player):
     if player.need_to_go == 0 :
         data_send = f"Broadcast \"Level {player.level} c\"\n"
         player.nb_r += 1
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         player.queue.append(data_send)
     elif player.need_to_go == 1 :
         going_forward(client_socket, player)
     elif player.need_to_go == 2 :
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif player.need_to_go == 3 :
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif player.need_to_go == 4 :
         turning_left(client_socket, player)
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif player.need_to_go == 5 :
         turning_left(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif player.need_to_go == 6 :
         turning_right(client_socket, player)
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     elif player.need_to_go == 7 :
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     elif player.need_to_go == 8 :
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     player.need_to_go = None
References going_forward(), turning_left(), and turning_right().
Referenced by moving_player().
going_forward()
def zappy_ai.going_forward (client_socket, player)
@brief Sends Forward to the socket and put back player.look to false and player.view to [], adds the send to the player.queue.
@param client_socket Socket where to send the string.
@param player Player class containing view, look and queue.
Definition at line 127 of file zappy_ai.py.
 def going_forward(client_socket, player):
     """
     @brief Sends Forward to the socket and put back player.look to false and player.view to [], adds the send to the player.queue.
     @param client_socket Socket where to send the string.
     @param player Player class containing view, look and queue.
     """
     data_send = "Forward\n"
     print(f"Sending : {data_send}", end="")
     client_socket.send(data_send.encode())
     player.look = False
     player.view = []
     player.queue.append(data_send)
Referenced by go_to_need(), moving_level(), and test_zappy_ai.TestZappyAI.test_going_forward().
incant_nb()
def zappy_ai.incant_nb (player)
Definition at line 644 of file zappy_ai.py.
 def incant_nb(player):
     if (player.level == 2 or player.level == 3) and player.nb_r >= 2 :
         return True
     if (player.level == 4 or player.level == 5) and player.nb_r >= 4 :
         return True
     if (player.level == 6 or player.level == 7) and player.nb_r >= 6 :
         return True
     return False
Referenced by command_received(), command_send(), and moving_player().
inventory()
def zappy_ai.inventory (player, data_rec)
Definition at line 413 of file zappy_ai.py.
 def inventory(player, data_rec):
     data = split_by_commas(data_rec)
     for item in data:
         if item.startswith("food"):
             _, quantity = item.split()
             player.starve = int(quantity)
             print(f"I have {player.starve} food", file=sys.stderr)
             return
References int, and split_by_commas().
Referenced by command_received().
looking()
def zappy_ai.looking (client_socket, player)
@brief Sends Look to the socket, adds the send to the player.queue and set player.look to true.
@param client_socket Socket where to send the string.
@param player Player class containing queue.
Definition at line 162 of file zappy_ai.py.
 def looking(client_socket, player):
     """
     @brief Sends Look to the socket, adds the send to the player.queue and set player.look to true.
     @param client_socket Socket where to send the string.
     @param player Player class containing queue.
     """
     data_send = "Look\n"
     print(f"Sending : {data_send}", end="")
     client_socket.send(data_send.encode())
     player.look = True
     player.queue.append(data_send)
Referenced by command_send(), and test_zappy_ai.TestZappyAI.test_looking().
moving_level()
def zappy_ai.moving_level (client_socket, player)
@brief Checks with the information in player.view where to move.
@param client_socket Socket where to potentially send information.
@param player Player class.
Definition at line 489 of file zappy_ai.py.
 def moving_level(client_socket, player):
     """
     @brief Checks with the information in player.view where to move.
     @param client_socket Socket where to potentially send information.
     @param player Player class.
     """
     indices = find_keyword_in_list(player.view, "food")
     if count_words_at_index(player.view, 2) > 0 :
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 6) > 0 and (check_stones(player, 6) != None or 6 in indices) and player.level >= 2 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 12) > 0 and (check_stones(player, 12) != None or 12 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 1) > 0 :
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 3) > 0 :
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 5) > 0 and (check_stones(player, 5) != None or 5 in indices) and player.level >= 2 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 7) > 0 and (check_stones(player, 7) != None or 7 in indices) and player.level >= 2 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 4) > 0 and (check_stones(player, 4) != None or 4 in indices) and player.level >= 2 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 8) > 0 and (check_stones(player, 8) != None or 8 in indices) and player.level >= 2 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 11) > 0 and (check_stones(player, 11) != None or 11 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 13) > 0 and (check_stones(player, 13) != None or 13 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 10) > 0 and (check_stones(player, 10) != None or 10 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 14) > 0 and (check_stones(player, 14) != None or 14 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 10) > 0 and (check_stones(player, 10) != None or 10 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_left(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
     elif count_words_at_index(player.view, 14) > 0 and (check_stones(player, 14) != None or 14 in indices) and player.level >= 3 :
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         turning_right(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
         going_forward(client_socket, player)
     else :
         r = random.random()
         if r > 0.4 :
             going_forward(client_socket, player)
         elif r > 0.2 :
             going_forward(client_socket, player)
             turning_left(client_socket, player)
             going_forward(client_socket, player)
         else :
             going_forward(client_socket, player)
             turning_right(client_socket, player)
             going_forward(client_socket, player)
References check_stones(), count_words_at_index(), find_keyword_in_list(), going_forward(), turning_left(), and turning_right().
Referenced by moving_player().
moving_player()
def zappy_ai.moving_player (client_socket, player)
@brief Checks the player level to know what move to do.
@param client_socket Socket where to potentially send information.
@param player Player class.
Definition at line 628 of file zappy_ai.py.
 def moving_player(client_socket, player):
     """
     @brief Checks the player level to know what move to do.
     @param client_socket Socket where to potentially send information.
     @param player Player class.
     """
     if player.need_to_go != None :
         if incant_nb(player) :
             player.incanting = True
             player.nb_r = 0
             player.need_to_go = None
             return
         go_to_need(client_socket, player)
         return
     moving_level(client_socket, player)
References go_to_need(), incant_nb(), and moving_level().
Referenced by command_send(), and test_zappy_ai.TestZappyAI.test_moving_player().
netcat_client()
def zappy_ai.netcat_client (host, port, name)
@brief What i should have called "Main", creates the socket, the player class, use select and has the main loop.
@param host IP address of the host.
@param port Port of the host.
@param name Name of the team to join.
Definition at line 696 of file zappy_ai.py.
 def netcat_client(host, port, name):
     """
     @brief What i should have called "Main", creates the socket, the player class, use select and has the main loop.
     @param host IP address of the host.
     @param port Port of the host.
     @param name Name of the team to join.
     """
     client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
     client_socket.connect((host, port))
     player = Player()
     sockets_to_read = [client_socket]
     print(f"Received: {client_socket.recv(1024).decode()}", end="")
     try:
         data_send = name + "\n"
         print(f"Sending : {data_send}", end="")
         client_socket.send(data_send.encode())
         while True:
             ready_to_read, _, _ = select.select(sockets_to_read, [], [], 0.1)
             if client_socket in ready_to_read:
                 data_rec = client_socket.recv(1024)
                 # print(f"Received: {data_rec.decode()}", end="")
                 if data_rec.decode() == "dead\n": # receptions
                     break
                 commands = data_rec.decode().splitlines(keepends=True)
                 for command in commands:
                     command_received(player, command.encode())
             # print(f"N : {player.need_to_go}")
             command_send(client_socket, player)
         print("Player session ended", file=sys.stderr)
     except KeyboardInterrupt:
         print("Closing...")
     finally:
         client_socket.close()
References command_received(), and command_send().
received_look()
def zappy_ai.received_look (player, data_rec)
@brief Based on the data received after using looking function, if the date is ko, player.look is set to false, else, player.view gets the result of the received data sent to split_by_commas function.
@param player Player class containing look and view.
@param data_rec String containing ko or a long string.
Definition at line 390 of file zappy_ai.py.
 def received_look(player, data_rec):
     """
     @brief Based on the data received after using looking function, if the date is ko, player.look is set to false, else, player.view gets the result of the received data sent to split_by_commas function.
     @param player Player class containing look and view.
     @param data_rec String containing ko or a long string.
     """
     if data_rec.decode() == "ko\n" :
         player.look = False
     else :
         player.view = split_by_commas(data_rec.decode())
References split_by_commas().
Referenced by command_received(), and test_zappy_ai.TestZappyAI.test_received_look().
reduce_max()
def zappy_ai.reduce_max (player)
Definition at line 401 of file zappy_ai.py.
 def reduce_max(player):
     if player.level == 2:
         player.max_linemate -= 1
     elif player.level == 3:
         player.max_linemate -= 1
         player.max_deraumere -= 1
         player.max_sibur -= 1
     elif player.level == 4:
         player.max_linemate -= 2
         player.max_sibur -= 1
         player.max_phiras -= 2
Referenced by command_received().
remove_element()
def zappy_ai.remove_element (strings, index, element)
@brief Removes a word in a list at a given index.
@param strings List of strings.
@param index Index where to delete the word.
@param element Word to delete in the list.
Definition at line 101 of file zappy_ai.py.
 def remove_element(strings, index, element):
     """
     @brief Removes a word in a list at a given index.
     @param strings List of strings.
     @param index Index where to delete the word.
     @param element Word to delete in the list.
     """
     if 0 <= index < len(strings):
         strings[index] = strings[index].replace(element, "", 1)
     else:
         raise IndexError("Index out of range")
Referenced by send_and_remove(), and test_zappy_ai.TestZappyAI.test_remove_element().
send_and_remove()
def zappy_ai.send_and_remove (client_socket, player, index, element)
@brief Sends a string to a socket and then calls remove_element, adds the send to the player.queue.
@param client_socket The socket where to send the string.
@param player The player class where the information to delete are.
@param index The index where to delete a word.
@param element A part of the message to send and the word to delete.
Definition at line 113 of file zappy_ai.py.
 def send_and_remove(client_socket, player, index, element):
     """
     @brief Sends a string to a socket and then calls remove_element, adds the send to the player.queue.
     @param client_socket The socket where to send the string.
     @param player The player class where the information to delete are.
     @param index The index where to delete a word.
     @param element A part of the message to send and the word to delete.
     """
     data_send = f"Take {element}\n"
     print(f"Sending: {data_send}", end="")
     client_socket.send(data_send.encode())
     remove_element(player.view, index, element)
     player.queue.append(data_send)
References remove_element().
Referenced by command_send(), and test_zappy_ai.TestZappyAI.test_send_and_remove().
split_by_commas()
def zappy_ai.split_by_commas (input_string)
@brief Splits the string received into a list.
@param input_string String to split.
@return List created from the string.
Definition at line 63 of file zappy_ai.py.
 def split_by_commas(input_string):
     """
     @brief Splits the string received into a list.
     @param input_string String to split.
     @return List created from the string.
     """
     input_string = input_string.replace('[', '').replace(']', '')
     items = input_string.split(',')
     cleaned_items = [item.strip() for item in items]
     return cleaned_items
Referenced by inventory(), received_look(), and test_zappy_ai.TestZappyAI.test_split_by_commas().
turning_left()
def zappy_ai.turning_left (client_socket, player)
@brief Sends Left to the socket, adds the send to the player.queue.
@param client_socket Socket where to send the string.
@param player Player class containing queue.
Definition at line 151 of file zappy_ai.py.
 def turning_left(client_socket, player):
     """
     @brief Sends Left to the socket, adds the send to the player.queue.
     @param client_socket Socket where to send the string.
     @param player Player class containing queue.
     """
     data_send = "Left\n"
     print(f"Sending : {data_send}", end="")
     client_socket.send(data_send.encode())
     player.queue.append(data_send)
Referenced by go_to_need(), moving_level(), and test_zappy_ai.TestZappyAI.test_turning_left().
turning_right()
def zappy_ai.turning_right (client_socket, player)
@brief Sends Right to the socket, adds the send to the player.queue.
@param client_socket Socket where to send the string.
@param player Player class containing queue.
Definition at line 140 of file zappy_ai.py.
 def turning_right(client_socket, player):
     """
     @brief Sends Right to the socket, adds the send to the player.queue.
     @param client_socket Socket where to send the string.
     @param player Player class containing queue.
     """
     data_send = "Right\n"
     print(f"Sending : {data_send}", end="")
     client_socket.send(data_send.encode())
     player.queue.append(data_send)
Referenced by go_to_need(), moving_level(), and test_zappy_ai.TestZappyAI.test_turning_right().
Variable Documentation
action
zappy_ai.action
Definition at line 753 of file zappy_ai.py.
args
zappy_ai.args = parser.parse_args()
Definition at line 756 of file zappy_ai.py.
Referenced by Test().
default
zappy_ai.default
Definition at line 752 of file zappy_ai.py.
help
zappy_ai.help
Definition at line 750 of file zappy_ai.py.
int
zappy_ai.int
Definition at line 750 of file zappy_ai.py.
Referenced by command_received(), and inventory().
missing_args
list zappy_ai.missing_args = [arg for arg in required_args if arg not in sys.argv]
Definition at line 744 of file zappy_ai.py.
parser
zappy_ai.parser = argparse.ArgumentParser(add_help=False)
Definition at line 749 of file zappy_ai.py.
required
zappy_ai.required
Definition at line 750 of file zappy_ai.py.
required_args
list zappy_ai.required_args = ['-p', '--port', '-n', '--name']
Definition at line 743 of file zappy_ai.py.
str
zappy_ai.str
Definition at line 751 of file zappy_ai.py.
True
zappy_ai.True
Definition at line 750 of file zappy_ai.py.
type
zappy_ai.type
Definition at line 750 of file zappy_ai.py.