PotatZap: Server/src/server/op_cli_ll.c File Reference
op_cli_ll.c File Reference
operations on the linked list of clients
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
client_t * find_client_and_prev (int cli_socket, client_t **prev_out)
int remove_found_client (client_t *prev, client_t *cli)
int remove_client (int cli_socket)
Function to remove a client from the linked list.
Detailed Description
operations on the linked list of clients
Definition in file op_cli_ll.c.
Function Documentation
find_client_and_prev()
client_t* find_client_and_prev (int cli_socket, client_t ** prev_out)
Definition at line 18 of file op_cli_ll.c.
 {
     server_t *server = get_instance();
     client_t *cli = server->clients;
     *prev_out = NULL;
     while (cli != NULL) {
         if (cli->socket == cli_socket) {
             return cli;
         }
         *prev_out = cli;
         cli = cli->next;
     }
     return NULL;
 }
References get_instance(), and server.
Referenced by remove_client().
remove_client()
int remove_client (int cli_socket)
Function to remove a client from the linked list.
Parameters
int cli_socket represent the client socket.
will remove the client from the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 50 of file op_cli_ll.c.
 {
     client_t *prev;
     client_t *cli = find_client_and_prev(cli_socket, &prev);
     if (remove_found_client(prev, cli) == 84)
         return 84;
     return 0;
 }
References find_client_and_prev(), and remove_found_client().
Referenced by read_buffer_to_list().
remove_found_client()
int remove_found_client (client_t * prev, client_t * cli)
Definition at line 34 of file op_cli_ll.c.
 {
     server_t *server = get_instance();
     if (cli == NULL)
         return 0;
     if (prev == NULL) {
         server->clients = cli->next;
     } else {
         prev->next = cli->next;
     }
     close(cli->socket);
     free(cli);
     return 0;
 }
References get_instance(), and server.
Referenced by remove_client().