PotatZap: Server/src/server/read_write_cmd.c File Reference
read_write_cmd.c File Reference
read and write command for the server
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
int max_cmd_cli (int cli_id)
int add_cmd_to_ll (int cli_id, const char *cmd, double execution_time)
void read_buffer_to_list (client_t *cli)
Function that detect command of the client and add it to the linked list.
int handle_clients (void)
Function that handle the clients.
Detailed Description
read and write command for the server
Definition in file read_write_cmd.c.
Function Documentation
add_cmd_to_ll()
int add_cmd_to_ll (int cli_id, const char * cmd, double execution_time)
Definition at line 35 of file read_write_cmd.c.
 {
     server_t *server = get_instance();
     command_t *new_command = malloc(sizeof(command_t));
     if (new_command == NULL) {
         perror("malloc");
         return 84;
     }
     if (max_cmd_cli(cli_id) == 84 || cmd[0] == '\0')
         return 84;
     new_command->cli_id = cli_id;
     new_command->command = strdup(cmd);
     if (new_command->command == NULL) {
         perror("strdup");
         free(new_command);
         return 84;
     }
     new_command->execution_time = execution_time;
     TAILQ_INSERT_TAIL(&server->commands, new_command, entries);
     return 0;
 }
References get_instance(), max_cmd_cli(), and server.
Referenced by read_buffer_to_list().
handle_clients()
int handle_clients (void)
Function that handle the clients.
Parameters
void no parameters are required.
will handle the clients and their commands to add them in the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 78 of file read_write_cmd.c.
 {
     server_t *server = get_instance();
     client_t *cli = server->clients;
     client_t *next = NULL;
     while (cli != NULL) {
         next = cli->next;
         if (cli->socket <= 0 || !FD_ISSET(cli->socket, &server->readfs)) {
             cli = next;
             continue;
         }
         read_buffer_to_list(cli);
         cli = next;
     }
     return 0;
 }
References get_instance(), read_buffer_to_list(), and server.
Referenced by run_server().
max_cmd_cli()
int max_cmd_cli (int cli_id)
Definition at line 18 of file read_write_cmd.c.
 {
     server_t *server = get_instance();
     client_t *cli = NULL;
     for (cli = server->clients; cli != NULL; cli = cli->next) {
         if (cli->socket == cli_id && cli->nb_commands < 10) {
             cli->nb_commands++;
             return 0;
         }
         if (cli->socket == cli_id && cli->nb_commands == 10) {
             return 84;
         }
     }
     return 84;
 }
References get_instance(), and server.
Referenced by add_cmd_to_ll().
read_buffer_to_list()
void read_buffer_to_list (client_t * cli)
Function that detect command of the client and add it to the linked list.
Parameters
client_t *cli the client entity that contains client informations.
client_t **prev the previous client entity.
server_t *server the server entity that contains server informations.
will check the command sent by the client, it's time of execution and add it to the linked list.
Returns
return nothing.
Definition at line 58 of file read_write_cmd.c.
 {
     double exec_time;
     char *buffer;
     char *command;
     char *command_type;
     buffer = read_cli_cmd(cli->socket);
     if (buffer == NULL) {
         remove_client(cli->socket);
         return;
     }
     command = strdup(buffer);
     command_type = strtok(command, " ");
     exec_time = detect_execution_time(command_type);
     add_cmd_to_ll(cli->socket, buffer, exec_time);
     free(buffer);
     free(command);
 }
References add_cmd_to_ll(), detect_execution_time(), read_cli_cmd(), and remove_client().
Referenced by handle_clients().