PotatZap: Server/src/server/read_and_print_cmd.c File Reference
read_and_print_cmd.c File Reference
read and write command for the server
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
char * read_from_socket (int cli_socket, int *bytes_read)
char * parse_command (char *cmd)
char * read_cli_cmd (int cli_socket)
Function to read the client command.
Detailed Description
read and write command for the server
Definition in file read_and_print_cmd.c.
Function Documentation
parse_command()
char* parse_command (char * cmd)
Definition at line 33 of file read_and_print_cmd.c.
 {
     char *parse_command = strtok(cmd, "\r\n");
     if (parse_command) {
         return strdup(parse_command);
     }
     return NULL;
 }
Referenced by read_cli_cmd().
read_cli_cmd()
char* read_cli_cmd (int cli_socket)
Function to read the client command.
Parameters
int cli_socket represent the client socket.
will read the client command.
Returns
return the command of the client.
Definition at line 43 of file read_and_print_cmd.c.
 {
     int bytes_read;
     char *cmd = read_from_socket(cli_socket, &bytes_read);
     char *result = NULL;
     if (cmd == NULL) {
         return NULL;
     }
     printf("Reading command from Client %d: %s\n", cli_socket, cmd);
     result = parse_command(cmd);
     free(cmd);
     return result;
 }
References parse_command(), and read_from_socket().
Referenced by read_buffer_to_list().
read_from_socket()
char* read_from_socket (int cli_socket, int * bytes_read)
Definition at line 17 of file read_and_print_cmd.c.
 {
     char *buffer = malloc(sizeof(char) * (1024 + 1));
     if (buffer == NULL) {
         return NULL;
     }
     *bytes_read = read(cli_socket, buffer, 1024);
     if (*bytes_read <= 0) {
         free(buffer);
         return NULL;
     }
     buffer[*bytes_read] = '\0';
     return buffer;
 }
Referenced by read_cli_cmd().