PotatZap: Server/src/server/run_server.c File Reference
run_server.c File Reference
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
#include "../../include/my.h"
Functions
void handle_sigint (int sig)
Function that handle the signal SIGINT.
int run_server (void)
Function that run the server.
Function Documentation
handle_sigint()
void handle_sigint (int sig)
Function that handle the signal SIGINT.
Parameters
int sig the signal to handle.
will close the server socket and exit the server if ctrl + c is detected.
Returns
void.
Definition at line 13 of file run_server.c.
 {
     server_t *server = get_instance();
     (void)sig;
     if (server == NULL)
         return;
     close(server->socket);
     exit(0);
 }
References get_instance(), and server.
Referenced by run_server().
run_server()
int run_server (void)
Function that run the server.
Parameters
void no parameters are required.
will run the server main loop to accept new clients and handle them.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 24 of file run_server.c.
 {
     server_t *server = get_instance();
     if (server == NULL)
         return 84;
     printf("server launched on port %d\n", server->port);
     signal(SIGINT, handle_sigint);
     while (1) {
         select_loop();
         if (FD_ISSET(server->socket, &server->readfs))
             accept_new_client();
         handle_clients();
         execute_cli_cmd();
     }
     return 0;
 }
References accept_new_client(), execute_cli_cmd(), get_instance(), handle_clients(), handle_sigint(), select_loop(), and server.
Referenced by main().