PotatZap: Server/src/server/select_cli.c File Reference
select_cli.c File Reference
select protocol for the server
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
Functions
int select_function (void)
Function that launch the select protocol.
void insert_new_client (client_t *cli, server_t *server)
int select_loop (void)
Function that prepare the select protocol.
Detailed Description
select protocol for the server
Definition in file select_cli.c.
Function Documentation
insert_new_client()
void insert_new_client (client_t * cli, server_t * server)
Definition at line 32 of file select_cli.c.
 {
     if (cli->socket > server->maxfd) {
         server->maxfd = cli->socket;
     }
 }
References server.
Referenced by select_loop().
select_function()
int select_function (void)
Function that launch the select protocol.
Parameters
void no parameters are required.
will launch the select protocol.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 16 of file select_cli.c.
 {
     struct server_s *server = get_instance();
     game_t *game = get_game_instance();
     struct timeval timeout;
     timeout.tv_sec = 0;
     timeout.tv_usec = 1000000 / game->freq;
     if (select(server->maxfd + 1, &server->readfs, &server->writefds,
         NULL, &timeout) < 0 && (errno != EINTR)) {
         perror("select");
         return 84;
     }
     return 0;
 }
References game_s::freq, game, get_game_instance(), get_instance(), and server.
Referenced by select_loop().
select_loop()
int select_loop (void)
Function that prepare the select protocol.
Parameters
void no parameters are required.
will clear and set the environment to receive commands.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 39 of file select_cli.c.
 {
     server_t *server = get_instance();
     client_t *cli = NULL;
     FD_ZERO(&server->readfs);
     FD_ZERO(&server->writefds);
     FD_SET(server->socket, &server->readfs);
     server->maxfd = server->socket;
     for (cli = server->clients; cli != NULL; cli = cli->next) {
         if (cli->socket > 0) {
             FD_SET(cli->socket, &server->readfs);
             FD_SET(cli->socket, &server->writefds);
             insert_new_client(cli, server);
         }
     }
     if (select_function() == 84) {
         return 84;
     }
     return 0;
 }
References get_instance(), insert_new_client(), select_function(), and server.
Referenced by run_server().