PotatZap: Server/src/server/send_cli_answers.c File Reference
send_cli_answers.c File Reference
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
int detect_client_waiting (int cli_socket)
Function to detect if the client is waiting.
void load_cli_and_exec (int cli_socket, char *command)
void execute_cli_cmd_bis (double start, command_t *cmd)
Function to execute the client commands.
void execute_cli_cmd (void)
Function to load the profile and execute the command.
Function Documentation
detect_client_waiting()
int detect_client_waiting (int client_socket)
Function to detect if the client is waiting.
Parameters
int cli_socket represent the client socket.
will detect if the client who sent the command is waiting or not.
Returns
return noting.
Definition at line 13 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     waiting_client_t *cli;
     TAILQ_FOREACH(cli, &server->waiting_list, entries) {
         if (cli->socket == cli_socket) {
             return 84;
         }
     }
     return 0;
 }
References get_instance(), and server.
Referenced by Test().
execute_cli_cmd()
void execute_cli_cmd (void)
Function to load the profile and execute the command.
Parameters
void no parameters are required.
will load and execute all of the commands received by all of the client.
Returns
return noting.
Definition at line 57 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     command_t *cmd;
     client_t *cli = NULL;
     double start = current_time_millis();
     TAILQ_FOREACH(cmd, &server->commands, entries)
         execute_cli_cmd_bis(start, cmd);
     cli = server->clients;
     for (; cli != NULL; cli = cli->next) {
         cli->nb_commands = 0;
     }
 }
References current_time_millis(), execute_cli_cmd_bis(), get_instance(), and server.
Referenced by run_server().
execute_cli_cmd_bis()
void execute_cli_cmd_bis (double start, command_t * cmd)
Function to execute the client commands.
Parameters
double current_time represent the current time in milliseconds.
command_t *cmd represent the command entity that contains command informations.
will call the main to execute the command sent if there is the time and after delete the command from the linked list.
Returns
return noting.
Definition at line 41 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     double now = current_time_millis();
     double end = start + cmd->execution_time;
     printf("Client ID: %d, Command: %s\n", cmd->cli_id, cmd->command);
     if (now < end) {
         load_cli_and_exec(cmd->cli_id, cmd->command);
         now = current_time_millis();
     }
     TAILQ_REMOVE(&server->commands, cmd, entries);
     free(cmd->command);
     free(cmd);
 }
References current_time_millis(), get_instance(), load_cli_and_exec(), and server.
Referenced by execute_cli_cmd().
load_cli_and_exec()
void load_cli_and_exec (int cli_socket, char * command)
Definition at line 26 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     client_t *cli = NULL;
     for (cli = server->clients; cli != NULL; cli = cli->next) {
         if (cli->socket == cli_socket && cli->status == false) {
             handle_cli_login(cli, command);
         }
         if (cli->socket == cli_socket && cli->status == true) {
             execute_game_cmd(cli_socket, command);
         }
     }
 }
References execute_game_cmd(), get_instance(), handle_cli_login(), and server.
Referenced by execute_cli_cmd_bis().