PotatZap: Server/include/server.h File Reference
server.h File Reference
Contains definitions of the server management functions.
#include "struct_client.h"
#include "struct_game.h"
#include "struct_server.h"
Functions
int init_server (void)
Function that init the server struct parameters.
int init_server_bis (void)
Function that init the construction process of the server.
int init_socket (void)
Function that init the socket of the server.
int init_server_launch (void)
Function that init the launch of the server.
int init_server_listen (void)
Function that init the listening of the server.
int run_server (void)
Function that run the server.
void handle_sigint (int sig)
Function that handle the signal SIGINT.
int accept_new_client (void)
Function that accept a new client connection.
int add_client (int client_socket)
Function that define the client parameters.
void define_client_parameters (client_t *new_client, int client_socket)
Function that define the client parameters.
int accept_loop (int new_socket, int nb_joueur, int index)
Function that check if the session is full.
int init_ll_error_handling (int new_socket)
Function that handles the error case of the initialisation of the ll.
int init_ll (int new_socket, int index)
Function that init the linked list of the server.
int add_to_ll_bis (int new_socket, int index)
Function that add the client to the linked list.
int add_to_ll (int new_socket, int index)
Function that add the client to the main linked list.
int add_to_waiting_list (int new_socket, const char *team)
Function that add the client to the waiting list.
int handle_clients (void)
Function that handle the clients.
int add_command_to_list (int cli_id, const char *cmd, double execution_time)
Function that add the client command to the related linked list.
void handle_client_disconnection (client_t **prev, client_t **cli, client_t **head)
Function that delete the client from the linked list.
void read_buffer_to_list (client_t *cli)
Function that detect command of the client and add it to the linked list.
int detect_max_command_capacity (int cli_id)
Function that detect the max command capacity of the client.
int select_loop (void)
Function that prepare the select protocol.
int select_function (void)
Function that launch the select protocol.
void handle_cli_login (client_t *cli, char *command)
Function to handle the client login phase.
int detect_team_validity (char *team_name, client_t *cli)
Function to check if the team name is valid or not.
int handle_team_full_status (client_t *cli, team_t *team, game_t *game, char *team_name)
Function to handle the team full status.
void execute_game_cmd (int cli_socket, char *command)
Function to execute the game commands.
int comp_cmd (char *command_type)
Function to compare the command type.
int comp_cmd_bis (char *command_type)
Function to compare the command type.
void execute_cli_cmd (void)
Function to load the profile and execute the command.
int detect_client_waiting (int client_socket)
Function to detect if the client is waiting.
void load_profile_and_exec (int cli_socket, char *command)
Function to load the profile and execute the command.
void execute_cli_cmd_bis (double start, command_t *cmd)
Function to execute the client commands.
double detect_execution_time (char *command)
Function to compute the execution time of a command.
double current_time_millis (void)
Function to get the current time in milliseconds.
int remove_client (int cli_socket)
Function to remove a client from the linked list.
char * read_cli_cmd (int cli_socket)
Function to read the client command.
Detailed Description
Contains definitions of the server management functions.
Definition in file server.h.
Function Documentation
accept_loop()
int accept_loop (int new_socket, int nb_joueur, int index)
Function that check if the session is full.
Parameters
int new_socket the socket of the new client.
int nb_joueur the number of players.
int index the index of the team.
will check if the session is full and add the client to the waiting list or accept the connection and join the game.
Returns
return 0 if everything's good or 84 if an error occured.
accept_new_client()
int accept_new_client (void)
Function that accept a new client connection.
Parameters
void no parameters are required.
will check if the client socket is ready and accept the new client connection.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 54 of file accept_cli.c.
 {
     server_t *server = get_instance();
     int new_socket = 0;
     if (FD_ISSET(server->socket, &server->readfs)) {
         new_socket = accept(server->socket, NULL, NULL);
         if (new_socket < 0) {
             perror("accept");
             return 84;
         }
         add_client(new_socket);
     }
     return 0;
 }
References add_client(), get_instance(), and server.
Referenced by run_server().
add_client()
int add_client (int client_socket)
Function that define the client parameters.
Parameters
client_t *new_client the new client.
int client_socket the socket of the client.
will define the client parameters.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 39 of file accept_cli.c.
 {
     client_t *new_client = malloc(sizeof(client_t));
     if (new_client == NULL) {
         perror("malloc");
         close(client_socket);
         return 84;
     }
     add_cli_to_ll(new_client, client_socket);
     printf("Added new client with socket %d\n", client_socket);
     write(new_client->socket, "WELCOME\r\n", strlen("WELCOME\r\n"));
     return 0;
 }
References add_cli_to_ll().
Referenced by accept_new_client().
add_command_to_list()
int add_command_to_list (int cli_id, const char * cmd, double execution_time)
Function that add the client command to the related linked list.
Parameters
int cli_socket the socket of the client.
will add the client command to the related linked list.
Returns
return the command of the client.
Referenced by Test().
add_to_ll()
int add_to_ll (int new_socket, int index)
Function that add the client to the main linked list.
Parameters
int new_socket the socket of the new client.
int index the index of the team.
will check if the linked list is empty and redirect to the best process to add to linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Referenced by Test().
add_to_ll_bis()
int add_to_ll_bis (int new_socket, int index)
Function that add the client to the linked list.
Parameters
int new_socket the socket of the new client.
int index the index of the team.
will add the client to the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Referenced by Test().
add_to_waiting_list()
int add_to_waiting_list (int new_socket, const char * team)
Function that add the client to the waiting list.
Parameters
int new_socket the socket of the new client.
int index the index of the team.
will add the client to the waiting list.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 17 of file waiting_list_ll.c.
 {
     server_t *server = get_instance();
     waiting_client_t *new_waiting_client = malloc(sizeof(waiting_client_t));
     if (new_waiting_client == NULL) {
         perror("malloc");
         close(new_socket);
         return 84;
     }
     new_waiting_client->socket = new_socket;
     new_waiting_client->team = strdup(team);
     if (new_waiting_client->team == NULL) {
         perror("strdup");
         close(new_socket);
         free(new_waiting_client);
         return 84;
     }
     TAILQ_INSERT_TAIL(&server->waiting_list, new_waiting_client, entries);
     return 0;
 }
References get_instance(), server, and team.
Referenced by handle_team_full(), and Test().
comp_cmd()
int comp_cmd (char * command_type)
Function to compare the command type.
Parameters
char *command_type represent the command type sent by the client.
will compare the command type.
Returns
return 0 if the command type match, and 1 if the command type doesn't match.
Definition at line 13 of file handling_game_command.c.
 {
     if (strcmp(command_type, "Left") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Look") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Broadcast") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Eject") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Take") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Set") == 0) {
         return 0;
     }
     return 1;
 }
Referenced by execute_game_cmd().
comp_cmd_bis()
int comp_cmd_bis (char * command_type)
Function to compare the command type.
Parameters
char *command_type represent the command type sent by the client.
will compare the command type.
Returns
return 0 if the command type match, and 1 if the command type doesn't match.
Definition at line 36 of file handling_game_command.c.
 {
     if (strcmp(command_type, "Forward") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Right") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Fork") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Incantation") == 0) {
         return 0;
     }
     if (strcmp(command_type, "Connect_nbr")) {
         return 0;
     }
     if (strcmp(command_type, "Inventory") == 0) {
         return 0;
     }
     return 1;
 }
Referenced by execute_game_cmd().
current_time_millis()
double current_time_millis (void)
Function to get the current time in milliseconds.
Parameters
void no parameters are required.
will get the current time in milliseconds.
Returns
return the current time in milliseconds.
Definition at line 36 of file timer.c.
 {
     struct timespec ts;
     if (clock_gettime(CLOCK_MONOTONIC, &ts) == 0) {
         return ts.tv_sec + (ts.tv_nsec / 1000000000.0);
     }
     return -1;
 }
Referenced by execute_cli_cmd(), and execute_cli_cmd_bis().
define_client_parameters()
void define_client_parameters (client_t * new_client, int client_socket)
Function that define the client parameters.
Parameters
client_t *new_client the new client.
int client_socket the socket of the client.
will define the client parameters and insert the client in the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
detect_client_waiting()
int detect_client_waiting (int client_socket)
Function to detect if the client is waiting.
Parameters
int cli_socket represent the client socket.
will detect if the client who sent the command is waiting or not.
Returns
return noting.
Definition at line 13 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     waiting_client_t *cli;
     TAILQ_FOREACH(cli, &server->waiting_list, entries) {
         if (cli->socket == cli_socket) {
             return 84;
         }
     }
     return 0;
 }
References get_instance(), and server.
Referenced by Test().
detect_execution_time()
double detect_execution_time (char * command)
Function to compute the execution time of a command.
Parameters
char *command represent the command sent by the client.
will detect if the command sent by the client require a specific execution time and compute it or if not return the default value.
Returns
return the execution time of the command.
Definition at line 13 of file timer.c.
 {
     game_t *game = get_game_instance();
     double result = 1000000.0;
     if (strcmp(command, "Forward") == 0 || strcmp(command, "Right") == 0 ||
         strcmp(command, "Left") == 0 || strcmp(command, "Look") == 0 ||
         strcmp(command, "Broadcast") == 0 || strcmp(command, "Eject") == 0 ||
         strcmp(command, "Take") == 0 || strcmp(command, "Set") == 0) {
         return 7.0 / game->freq;
     }
     if (strcmp(command, "Inventory") == 0) {
         return 1.0 / game->freq;
     }
     if (strcmp(command, "Fork") == 0) {
         return 42.0 / game->freq;
     }
     if (strcmp(command, "Incantation") == 0) {
         return 300.0 / game->freq;
     }
     return result;
 }
References game_s::freq, game, and get_game_instance().
Referenced by read_buffer_to_list(), and Test().
detect_max_command_capacity()
int detect_max_command_capacity (int cli_id)
Function that detect the max command capacity of the client.
Parameters
int cli_id the client id.
will check if the client has reached the maximum command capacity and if not increment the number of commands to authorize a new one.
Returns
return 0 if everything's good or 84 if an error occured.
detect_team_validity()
int detect_team_validity (char * team_name, client_t * cli)
Function to check if the team name is valid or not.
Parameters
char *team_name represent the team name sent by the client.
client_t *cli represent the client entity that contains client informations.
will check if the team name exists or not and so change connected status of the client.
Returns
return 0 if there is no error, and 84 if there is an error.
Definition at line 36 of file handling_login_phase.c.
 {
     game_t *game = get_game_instance();
     for (int i = 0; i < game->nb_teams; i++) {
         if (strcmp(game->teams[i]->name, team_name) == 0) {
             cli->status = true;
             cli->team = strdup(team_name);
             return handle_team_full(cli, game->teams[i], team_name);
         }
     }
     return 84;
 }
References game, get_game_instance(), handle_team_full(), team_s::name, game_s::nb_teams, and game_s::teams.
Referenced by handle_cli_login().
execute_cli_cmd()
void execute_cli_cmd (void)
Function to load the profile and execute the command.
Parameters
void no parameters are required.
will load and execute all of the commands received by all of the client.
Returns
return noting.
Definition at line 57 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     command_t *cmd;
     client_t *cli = NULL;
     double start = current_time_millis();
     TAILQ_FOREACH(cmd, &server->commands, entries)
         execute_cli_cmd_bis(start, cmd);
     cli = server->clients;
     for (; cli != NULL; cli = cli->next) {
         cli->nb_commands = 0;
     }
 }
References current_time_millis(), execute_cli_cmd_bis(), get_instance(), and server.
Referenced by run_server().
execute_cli_cmd_bis()
void execute_cli_cmd_bis (double start, command_t * cmd)
Function to execute the client commands.
Parameters
double current_time represent the current time in milliseconds.
command_t *cmd represent the command entity that contains command informations.
will call the main to execute the command sent if there is the time and after delete the command from the linked list.
Returns
return noting.
Definition at line 41 of file send_cli_answers.c.
 {
     server_t *server = get_instance();
     double now = current_time_millis();
     double end = start + cmd->execution_time;
     printf("Client ID: %d, Command: %s\n", cmd->cli_id, cmd->command);
     if (now < end) {
         load_cli_and_exec(cmd->cli_id, cmd->command);
         now = current_time_millis();
     }
     TAILQ_REMOVE(&server->commands, cmd, entries);
     free(cmd->command);
     free(cmd);
 }
References current_time_millis(), get_instance(), load_cli_and_exec(), and server.
Referenced by execute_cli_cmd().
execute_game_cmd()
void execute_game_cmd (int cli_socket, char * command)
Function to execute the game commands.
Parameters
int cli_socket represent the client socket.
char *command represent the command sent by the client.
will execute the game commands.
Returns
return noting.
Definition at line 59 of file handling_game_command.c.
 {
     char *buffer = strdup(command);
     char *command_type = strtok(buffer, " ");
     int result = -1;
     cli_socket = cli_socket;
     result = comp_cmd_bis(command_type);
     if (result == 1)
         comp_cmd(command_type);
 }
References comp_cmd(), and comp_cmd_bis().
Referenced by load_cli_and_exec().
handle_cli_login()
void handle_cli_login (client_t * cli, char * command)
Function to handle the client login phase.
Parameters
client_t *cli represent the client entity that contains client informations.
char *command represent the team name sent by the client.
will check if the team name is valid and if the team is full or not.
Returns
return noting.
Definition at line 50 of file handling_login_phase.c.
 {
     char *msg = "Wrong team name, please try again\r\n";
     if (cli->status == false && detect_team_validity(command, cli) == 0)
         return;
     if (cli->status == false && detect_team_validity(command, cli) == 84) {
         write(cli->socket, msg, strlen(msg));
         return;
     }
 }
References detect_team_validity().
Referenced by load_cli_and_exec().
handle_client_disconnection()
void handle_client_disconnection (client_t ** prev, client_t ** cli, client_t ** head)
Function that delete the client from the linked list.
Parameters
client_t **prev the previous client entity.
client_t **cli the client entity that contains client informations.
client_t **head the head of the linked list.
will delete the client from the linked list.
Returns
return nothing.
handle_clients()
int handle_clients (void)
Function that handle the clients.
Parameters
void no parameters are required.
will handle the clients and their commands to add them in the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 78 of file read_write_cmd.c.
 {
     server_t *server = get_instance();
     client_t *cli = server->clients;
     client_t *next = NULL;
     while (cli != NULL) {
         next = cli->next;
         if (cli->socket <= 0 || !FD_ISSET(cli->socket, &server->readfs)) {
             cli = next;
             continue;
         }
         read_buffer_to_list(cli);
         cli = next;
     }
     return 0;
 }
References get_instance(), read_buffer_to_list(), and server.
Referenced by run_server().
handle_sigint()
void handle_sigint (int sig)
Function that handle the signal SIGINT.
Parameters
int sig the signal to handle.
will close the server socket and exit the server if ctrl + c is detected.
Returns
void.
Definition at line 13 of file run_server.c.
 {
     server_t *server = get_instance();
     (void)sig;
     if (server == NULL)
         return;
     close(server->socket);
     exit(0);
 }
References get_instance(), and server.
Referenced by run_server().
handle_team_full_status()
int handle_team_full_status (client_t * cli, team_t * team, game_t * game, char * team_name)
Function to handle the team full status.
Parameters
client_t *cli represent the client entity that contains client informations.
team_t *team represent the team entity that contains team informations.
game_t *game represent the game entity that contains game informations.
char *team_name represent the team name sent by the client.
will check if the team is full or not and so change the team status. It Will put the client in the waiting list if the team is full.
Returns
return 0 always.
init_ll()
int init_ll (int new_socket, int index)
Function that init the linked list of the server.
Parameters
int new_socket the socket of the new client.
int index the index of the team.
will init the linked list of the server and add the first element in the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Referenced by Test().
init_ll_error_handling()
int init_ll_error_handling (int new_socket)
Function that handles the error case of the initialisation of the ll.
Parameters
int new_socket the socket of the new client.
will return 84 if the server's instance or the game is instance is non existant.
Returns
return 0 if everything's good or 84 if an error occured.
init_server()
int init_server (void)
Function that init the server struct parameters.
Parameters
void no parameters are required.
will set the components of the server structure to their default values, init the different linked list and will call the init_server_bis function to init the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 78 of file init_server.c.
 {
     server_t *server = get_instance();
     if (server == NULL) {
         fprintf(stderr, "Error: server non existant\n");
         return 84;
     }
     server->maxfd = 0;
     server->nb_players = 0;
     server->clients = NULL;
     TAILQ_INIT(&server->waiting_list);
     TAILQ_INIT(&server->commands);
     if (init_server_bis() == 84) {
         fprintf(stderr, "Error: server init failed\n");
         return 84;
     }
     return 0;
 }
References get_instance(), init_server_bis(), and server.
Referenced by main(), and Test().
init_server_bis()
int init_server_bis (void)
Function that init the construction process of the server.
Parameters
void no parameters are required.
will call all of the necessary functions to create and launch the server. Such as fill the sockeaddr structure
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 60 of file init_server.c.
 {
     server_t *server = get_instance();
     if (init_socket() == 84) {
         fprintf(stderr, "Error: socket creation failed\n");
         return 84;
     }
     server->sockaddr.sin_family = AF_INET;
     server->sockaddr.sin_addr.s_addr = INADDR_ANY;
     server->sockaddr.sin_port = htons(server->port);
     if (init_server_launch() == 84) {
         fprintf(stderr, "Error: server launch failed\n");
         return 84;
     }
     return 0;
 }
References get_instance(), init_server_launch(), init_socket(), and server.
Referenced by init_server(), and Test().
init_server_launch()
int init_server_launch (void)
Function that init the launch of the server.
Parameters
void no parameters are required.
will bind the server to the address and port, set the socket to non blocking and will call the init_server_listen function to listen to the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 28 of file init_server.c.
 {
     server_t *server = get_instance();
     if (bind(server->socket, (struct sockaddr *)&server->sockaddr,
         sizeof(server->sockaddr)) < 0) {
         perror("bind");
         return 84;
     }
     if (init_server_listen() == 84)
         return 84;
     return 0;
 }
References get_instance(), init_server_listen(), and server.
Referenced by init_server_bis(), and Test().
init_server_listen()
int init_server_listen (void)
Function that init the listening of the server.
Parameters
void no parameters are required.
will listen to the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 17 of file init_server.c.
 {
     server_t *server = get_instance();
     if (listen(server->socket, 3) < 0) {
         perror("listen");
         return 84;
     }
     return 0;
 }
References get_instance(), and server.
Referenced by init_server_launch(), and Test().
init_socket()
int init_socket (void)
Function that init the socket of the server.
Parameters
void no parameters are required.
will create the socket of the server.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 42 of file init_server.c.
 {
     server_t *server = get_instance();
     int opt = 1;
     server->socket = socket(AF_INET, SOCK_STREAM, 0);
     if (server->socket == -1) {
         perror("socket");
         return 84;
     }
     if (setsockopt(server->socket, SOL_SOCKET,
         SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt)) < 0) {
         perror("Setsockopt failed");
         return 84;
     }
     return 0;
 }
References get_instance(), and server.
Referenced by init_server_bis(), and Test().
load_profile_and_exec()
void load_profile_and_exec (int cli_socket, char * command)
Function to load the profile and execute the command.
Parameters
int cli_socket represent the client socket.
char *command represent the command sent by the client.
will find the profile link to the client socket and will redirect the client to the right process if the client is connected or not.
Returns
return noting.
read_buffer_to_list()
void read_buffer_to_list (client_t * cli)
Function that detect command of the client and add it to the linked list.
Parameters
client_t *cli the client entity that contains client informations.
client_t **prev the previous client entity.
server_t *server the server entity that contains server informations.
will check the command sent by the client, it's time of execution and add it to the linked list.
Returns
return nothing.
Definition at line 58 of file read_write_cmd.c.
 {
     double exec_time;
     char *buffer;
     char *command;
     char *command_type;
     buffer = read_cli_cmd(cli->socket);
     if (buffer == NULL) {
         remove_client(cli->socket);
         return;
     }
     command = strdup(buffer);
     command_type = strtok(command, " ");
     exec_time = detect_execution_time(command_type);
     add_cmd_to_ll(cli->socket, buffer, exec_time);
     free(buffer);
     free(command);
 }
References add_cmd_to_ll(), detect_execution_time(), read_cli_cmd(), and remove_client().
Referenced by handle_clients().
read_cli_cmd()
char* read_cli_cmd (int cli_socket)
Function to read the client command.
Parameters
int cli_socket represent the client socket.
will read the client command.
Returns
return the command of the client.
Definition at line 43 of file read_and_print_cmd.c.
 {
     int bytes_read;
     char *cmd = read_from_socket(cli_socket, &bytes_read);
     char *result = NULL;
     if (cmd == NULL) {
         return NULL;
     }
     printf("Reading command from Client %d: %s\n", cli_socket, cmd);
     result = parse_command(cmd);
     free(cmd);
     return result;
 }
References parse_command(), and read_from_socket().
Referenced by read_buffer_to_list().
remove_client()
int remove_client (int cli_socket)
Function to remove a client from the linked list.
Parameters
int cli_socket represent the client socket.
will remove the client from the linked list.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 50 of file op_cli_ll.c.
 {
     client_t *prev;
     client_t *cli = find_client_and_prev(cli_socket, &prev);
     if (remove_found_client(prev, cli) == 84)
         return 84;
     return 0;
 }
References find_client_and_prev(), and remove_found_client().
Referenced by read_buffer_to_list().
run_server()
int run_server (void)
Function that run the server.
Parameters
void no parameters are required.
will run the server main loop to accept new clients and handle them.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 24 of file run_server.c.
 {
     server_t *server = get_instance();
     if (server == NULL)
         return 84;
     printf("server launched on port %d\n", server->port);
     signal(SIGINT, handle_sigint);
     while (1) {
         select_loop();
         if (FD_ISSET(server->socket, &server->readfs))
             accept_new_client();
         handle_clients();
         execute_cli_cmd();
     }
     return 0;
 }
References accept_new_client(), execute_cli_cmd(), get_instance(), handle_clients(), handle_sigint(), select_loop(), and server.
Referenced by main().
select_function()
int select_function (void)
Function that launch the select protocol.
Parameters
void no parameters are required.
will launch the select protocol.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 16 of file select_cli.c.
 {
     struct server_s *server = get_instance();
     game_t *game = get_game_instance();
     struct timeval timeout;
     timeout.tv_sec = 0;
     timeout.tv_usec = 1000000 / game->freq;
     if (select(server->maxfd + 1, &server->readfs, &server->writefds,
         NULL, &timeout) < 0 && (errno != EINTR)) {
         perror("select");
         return 84;
     }
     return 0;
 }
References game_s::freq, game, get_game_instance(), get_instance(), and server.
Referenced by select_loop().
select_loop()
int select_loop (void)
Function that prepare the select protocol.
Parameters
void no parameters are required.
will clear and set the environment to receive commands.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 39 of file select_cli.c.
 {
     server_t *server = get_instance();
     client_t *cli = NULL;
     FD_ZERO(&server->readfs);
     FD_ZERO(&server->writefds);
     FD_SET(server->socket, &server->readfs);
     server->maxfd = server->socket;
     for (cli = server->clients; cli != NULL; cli = cli->next) {
         if (cli->socket > 0) {
             FD_SET(cli->socket, &server->readfs);
             FD_SET(cli->socket, &server->writefds);
             insert_new_client(cli, server);
         }
     }
     if (select_function() == 84) {
         return 84;
     }
     return 0;
 }
References get_instance(), insert_new_client(), select_function(), and server.
Referenced by run_server().