PotatZap: Server/tests/unit-tests/test_accept_cli.c File Reference
test_accept_cli.c File Reference
#include <criterion/criterion.h>
#include <criterion/redirect.h>
#include <criterion/assert.h>
#include "../../include/my.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
#include "../../include/struct_server.h"
#include "../../include/struct_client.h"
#include <time.h>
Functions
void setup (void)
void teardown (void)
TestSuite (accept_cli,.init=setup,.fini=teardown)
Test (accept_cli, test_init_ll)
Test (accept_cli, test_add_to_ll_bis)
Test (accept_cli, test_add_to_ll)
Test (accept_cli, test_add_to_waiting_list)
Variables
server_t * server_instance
game_t * game_instance
team_t * team1
Function Documentation
setup()
void setup (void)
Definition at line 22 of file test_accept_cli.c.
                  {
     server_instance = get_instance();
     game_instance = get_game_instance();
     team1 = malloc(sizeof(team_t));
     team1->name = strdup("team1");
     team1->max_clients = 5;
     team1->cpt_egg = 1;
     game_instance->nb_teams = 1;
     game_instance->teams = malloc(sizeof(team_t *));
     game_instance->teams[0] = team1;
     game_instance->width = 100;
     game_instance->height = 100;
     server_instance->socket = 0;
     server_instance->clients = NULL;
     TAILQ_INIT(&server_instance->waiting_list);
     FD_ZERO(&server_instance->readfs);
 }
References team_s::cpt_egg, game_instance, get_game_instance(), get_instance(), game_s::height, team_s::max_clients, team_s::name, game_s::nb_teams, server_instance, team1, game_s::teams, and game_s::width.
teardown()
void teardown (void)
Definition at line 44 of file test_accept_cli.c.
                     {
     client_t *current = server_instance->clients;
     while (current) {
         client_t *tmp = current;
         current = current->next;
         free(tmp);
     }
     server_instance->clients = NULL;
     while (!TAILQ_EMPTY(&server_instance->waiting_list)) {
         waiting_client_t *wclient = TAILQ_FIRST(&server_instance->waiting_list);
         TAILQ_REMOVE(&server_instance->waiting_list, wclient, entries);
         free(wclient->team);
         free(wclient);
     }
     free(team1->name);
     free(team1);
     free(game_instance->teams);
     game_instance->teams = NULL;
 }
References game_instance, team_s::name, server_instance, team1, and game_s::teams.
Test() [1/4]
Test (accept_cli , test_add_to_ll)
Definition at line 106 of file test_accept_cli.c.
{
     int result = add_to_ll(1, 0);
     cr_assert_eq(result, 0, "Expected add_to_ll to return 0");
     cr_assert_not_null(server_instance->clients, "Expected server clients to be initialized");
     int new_socket = 2;
     result = add_to_ll(new_socket, 0);
     cr_assert_eq(result, 0, "Expected add_to_ll to return 0 when adding second client");
     cr_assert_not_null(server_instance->clients->next, "Expected new client to be added to the linked list");
 }
References add_to_ll(), and server_instance.
Test() [2/4]
Test (accept_cli , test_add_to_ll_bis)
Definition at line 96 of file test_accept_cli.c.
{
     init_ll(1, 0);
     int new_socket = 2;
     int result = add_to_ll_bis(new_socket, 0);
     cr_assert_eq(result, 0, "Expected add_to_ll_bis to return 0");
     cr_assert_not_null(server_instance->clients->next, "Expected new client to be added to the linked list");
     cr_assert_eq(server_instance->clients->next->socket, new_socket, "Expected new client socket to match");
     cr_assert_str_eq(server_instance->clients->next->team, "team1", "Expected new client team to match");
 }
References add_to_ll_bis(), init_ll(), and server_instance.
Test() [3/4]
Test (accept_cli , test_add_to_waiting_list)
Definition at line 117 of file test_accept_cli.c.
{
     int result = add_to_waiting_list(1, "team1");
     cr_assert_eq(result, 0, "Expected add_to_waiting_list to return 0");
     cr_assert_not_null(TAILQ_FIRST(&server_instance->waiting_list), "Expected new waiting client to be added");
     cr_assert_eq(TAILQ_FIRST(&server_instance->waiting_list)->socket, 1, "Expected waiting client socket to match");
     cr_assert_str_eq(TAILQ_FIRST(&server_instance->waiting_list)->team, "team1", "Expected waiting client team to match");
 }
References add_to_waiting_list(), and server_instance.
Test() [4/4]
Test (accept_cli , test_init_ll)
Definition at line 88 of file test_accept_cli.c.
{
     int result = init_ll(1, 0);
     cr_assert_eq(result, 0, "Expected init_ll to return 0");
     cr_assert_not_null(server_instance->clients, "Expected server clients to be initialized");
     cr_assert_eq(server_instance->clients->socket, 1, "Expected client socket to match");
     cr_assert_str_eq(server_instance->clients->team, "team1", "Expected client team to match");
 }
References init_ll(), and server_instance.
TestSuite()
TestSuite (accept_cli , . init = setup, . fini = teardown)
Variable Documentation
game_instance
game_t* game_instance
Definition at line 19 of file test_accept_cli.c.
Referenced by setup(), and teardown().
server_instance
server_t* server_instance
Definition at line 18 of file test_accept_cli.c.
Referenced by setup(), teardown(), and Test().
team1
team_t* team1
Definition at line 20 of file test_accept_cli.c.
Referenced by setup(), and teardown().