PotatZap: Server/tests/unit-tests/test_command_detection.c File Reference
test_command_detection.c File Reference
#include <criterion/criterion.h>
#include <criterion/redirect.h>
#include <criterion/assert.h>
#include "../../include/my.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
#include "../../include/struct_server.h"
#include "../../include/struct_client.h"
Functions
void setup_command_collect (void)
TestSuite (command_collect,.init=setup_command_collect)
Test (command_collect, test_adding_command_to_ll)
Variables
server_t * server_collect
game_t * game_collect
team_t * team_collect
Function Documentation
setup_command_collect()
void setup_command_collect (void)
Definition at line 21 of file test_command_detection.c.
{
     server_collect = get_instance();
     game_collect = get_game_instance();
     team_collect = malloc(sizeof(team_t));
     team_collect->name = strdup("team");
     team_collect->max_clients = 5;
     team_collect->cpt_egg = 1;
     game_collect->nb_teams = 1;
     game_collect->teams = malloc(sizeof(team_t *));
     game_collect->teams[0] = team_collect;
     game_collect->width = 100;
     game_collect->height = 100;
     server_collect->socket = 0;
     server_collect->clients = NULL;
     TAILQ_INIT(&server_collect->waiting_list);
     TAILQ_INIT(&server_collect->commands);
     FD_ZERO(&server_collect->readfs);
     // Add multiple test clients
     client_t *client1 = malloc(sizeof(client_t));
     client1->socket = 1;
     client1->nb_commands = 0;
     client1->next = NULL;
     server_collect->clients = client1;
     client_t *client2 = malloc(sizeof(client_t));
     client2->socket = 2;
     client2->nb_commands = 0;
     client2->next = NULL;
     client1->next = client2;
 }
References team_s::cpt_egg, game_collect, get_game_instance(), get_instance(), game_s::height, team_s::max_clients, team_s::name, game_s::nb_teams, server_collect, team_collect, game_s::teams, and game_s::width.
Test()
Test (command_collect , test_adding_command_to_ll)
Definition at line 59 of file test_command_detection.c.
 {
     cr_assert_eq(add_command_to_list(1, "bonjour", 10000), 0);
     cr_assert_eq(add_command_to_list(1, "", 10000), 84);
     command_t *command = TAILQ_FIRST(&server_collect->commands);
     cr_assert_not_null(command);
     cr_assert_eq(command->cli_id, 1);
     cr_assert_str_eq(command->command, "bonjour");
     cr_assert_eq(command->execution_time, 10000);
     client_t *client1 = server_collect->clients;
     client1->nb_commands = 10;
     cr_assert_eq(add_command_to_list(1, "bonjour", 10000), 84);
 }
References add_command_to_list(), and server_collect.
TestSuite()
TestSuite (command_collect , . init = setup_command_collect)
Variable Documentation
game_collect
game_t* game_collect
Definition at line 18 of file test_command_detection.c.
Referenced by setup_command_collect().
server_collect
server_t* server_collect
Definition at line 17 of file test_command_detection.c.
Referenced by setup_command_collect(), and Test().
team_collect
team_t* team_collect
Definition at line 19 of file test_command_detection.c.
Referenced by setup_command_collect().