PotatZap: Server/tests/unit-tests/test_singleton.c File Reference
test_singleton.c File Reference
#include <criterion/criterion.h>
#include <criterion/redirect.h>
#include <criterion/assert.h>
#include "../../include/my.h"
#include "../../include/handle_flags.h"
#include "../../include/get_instance.h"
Functions
Test (get_instance, test_get_instance)
Test (get_map_instance, test_get_map_instance)
Test (get_game_instance, test_get_game_instance)
Function Documentation
Test() [1/3]
Test (get_game_instance , test_get_game_instance)
Definition at line 43 of file test_singleton.c.
{
     char *av[] = { "./zappy_server", "-p", "1234", "-x", "100", "-y", "100", "-n", "team1", "-c", "10", "-f", "10" };
     handle_flags(13, av);
     game_t *game_instance1 = get_game_instance();
     game_t *game_instance2 = get_game_instance();
     cr_assert_not_null(game_instance1, "Expected get_game_instance() to return a non-null pointer");
     cr_assert_eq(game_instance1, game_instance2, "Expected get_game_instance() to return the same pointer on multiple calls");
     cr_assert_eq(game_instance1->width, 100);
     cr_assert_eq(game_instance1->height, 100);
     cr_assert_eq(game_instance1->freq, 10);
     cr_assert_eq(game_instance1->nb_teams, 1);
 }
References game_s::freq, get_game_instance(), handle_flags(), game_s::height, game_s::nb_teams, and game_s::width.
Test() [2/3]
Test (get_instance , test_get_instance)
Definition at line 16 of file test_singleton.c.
{
     char *av[] = { "./zappy_server", "-p", "1234", "-x", "100", "-y", "100", "-n", "team1", "-c", "10", "-f", "50" };
     handle_flags(13, av);
     server_t *instance1 = get_instance();
     server_t *instance2 = get_instance();
     cr_assert_not_null(instance1, "Expected get_instance() to return a non-null pointer");
     cr_assert_eq(instance1, instance2, "Expected get_instance() to return the same pointer on multiple calls");
     cr_assert_eq(instance1->port, 1234);
 }
References get_instance(), and handle_flags().
Test() [3/3]
Test (get_map_instance , test_get_map_instance)
Definition at line 31 of file test_singleton.c.
{
     char *av[] = { "./zappy_server", "-p", "1234", "-x", "100", "-y", "100", "-n", "team1", "-c", "10", "-f", "50" };
     handle_flags(13, av);
     map_t *map_instance1 = get_map_instance();
     map_t *map_instance2 = get_map_instance();
     cr_assert_not_null(map_instance1, "Expected get_map_instance() to return a non-null pointer");
     cr_assert_eq(map_instance1, map_instance2, "Expected get_map_instance() to return the same pointer on multiple calls");
 }
References get_map_instance(), and handle_flags().