PotatZap: Server/tests/unit-tests/test_init_server.c File Reference
test_init_server.c File Reference
#include <criterion/criterion.h>
#include <criterion/redirect.h>
#include <criterion/assert.h>
#include "../../include/my.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
#include "../../include/struct_server.h"
#include "../../include/struct_client.h"
#include <time.h>
Functions
int is_positive (int value)
void setup_server ()
Test (server_tests, test_init_socket_success)
Test (server_tests, test_init_server_launch_success)
Test (server_tests, test_init_server_listen_success)
Test (server_tests, test_init_server_bis_success)
Test (server_tests, test_init_server_success)
Function Documentation
is_positive()
int is_positive (int value)
Definition at line 18 of file test_init_server.c.
{
     return value > 0;
 }
setup_server()
void setup_server ()
Definition at line 22 of file test_init_server.c.
                     {
     server_t *server = get_instance();
     server->socket = -1;
     srand(time(NULL));
     server->port = 1024 + rand() % (65535 - 1024);
 }
References get_instance(), and server.
Referenced by Test().
Test() [1/5]
Test (server_tests , test_init_server_bis_success)
Definition at line 59 of file test_init_server.c.
{
     setup_server();
     server_t *server = get_instance();
     cr_assert_eq(init_server_bis(), 0, "init_server_bis should return 0 on success");
     cr_assert_neq(server->port, 0, "port should be set to a non-zero value");
 }
References get_instance(), init_server_bis(), server, and setup_server().
Test() [2/5]
Test (server_tests , test_init_server_launch_success)
Definition at line 37 of file test_init_server.c.
{
     int opt = 1;
     setup_server();
     server_t *server = get_instance();
     server->socket = socket(AF_INET, SOCK_STREAM, 0);
     setsockopt(server->socket, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt));
     server->sockaddr.sin_family = AF_INET;
     server->sockaddr.sin_addr.s_addr = INADDR_ANY;
     server->sockaddr.sin_port = htons(server->port);
     cr_assert_eq(init_server_launch(), 0, "init_server_launch should return 0 on success");
 }
References get_instance(), init_server_launch(), server, and setup_server().
Test() [3/5]
Test (server_tests , test_init_server_listen_success)
Definition at line 51 of file test_init_server.c.
{
     setup_server();
     server_t *server = get_instance();
     server->socket = socket(AF_INET, SOCK_STREAM, 0);
     cr_assert_eq(init_server_listen(), 0, "init_server_listen should return 0 on success");
 }
References get_instance(), init_server_listen(), server, and setup_server().
Test() [4/5]
Test (server_tests , test_init_server_success)
Definition at line 67 of file test_init_server.c.
{
     setup_server();
     server_t *server = get_instance();
     cr_assert_eq(init_server(), 0, "init_server should return 0 on success");
     cr_assert_eq(server->maxfd, 0, "maxfd should be initialized to 0");
     cr_assert_eq(server->nb_players, 0, "nb_players should be initialized to 0");
     cr_assert_null(server->clients, "clients should be initialized to NULL");
     cr_log_info("Server started on port %d", server->port);
 }
References get_instance(), init_server(), server, and setup_server().
Test() [5/5]
Test (server_tests , test_init_socket_success)
Definition at line 29 of file test_init_server.c.
{
     setup_server();
     server_t *server = get_instance();
     cr_assert_eq(init_socket(), 0, "init_socket should return 0 on success");
     cr_assert_neq(server->socket, -1, "socket should be initialized");
 }
References get_instance(), init_socket(), server, and setup_server().