PotatZap: Server/src/server/timer.c File Reference
timer.c File Reference
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/my.h"
#include "../../include/server.h"
Functions
double detect_execution_time (char *command)
Function to compute the execution time of a command.
double current_time_millis (void)
Function to get the current time in milliseconds.
Function Documentation
current_time_millis()
double current_time_millis (void)
Function to get the current time in milliseconds.
Parameters
void no parameters are required.
will get the current time in milliseconds.
Returns
return the current time in milliseconds.
Definition at line 36 of file timer.c.
 {
     struct timespec ts;
     if (clock_gettime(CLOCK_MONOTONIC, &ts) == 0) {
         return ts.tv_sec + (ts.tv_nsec / 1000000000.0);
     }
     return -1;
 }
Referenced by execute_cli_cmd(), and execute_cli_cmd_bis().
detect_execution_time()
double detect_execution_time (char * command)
Function to compute the execution time of a command.
Parameters
char *command represent the command sent by the client.
will detect if the command sent by the client require a specific execution time and compute it or if not return the default value.
Returns
return the execution time of the command.
Definition at line 13 of file timer.c.
 {
     game_t *game = get_game_instance();
     double result = 1000000.0;
     if (strcmp(command, "Forward") == 0 || strcmp(command, "Right") == 0 ||
         strcmp(command, "Left") == 0 || strcmp(command, "Look") == 0 ||
         strcmp(command, "Broadcast") == 0 || strcmp(command, "Eject") == 0 ||
         strcmp(command, "Take") == 0 || strcmp(command, "Set") == 0) {
         return 7.0 / game->freq;
     }
     if (strcmp(command, "Inventory") == 0) {
         return 1.0 / game->freq;
     }
     if (strcmp(command, "Fork") == 0) {
         return 42.0 / game->freq;
     }
     if (strcmp(command, "Incantation") == 0) {
         return 300.0 / game->freq;
     }
     return result;
 }
References game_s::freq, game, and get_game_instance().
Referenced by read_buffer_to_list(), and Test().