PotatZap: Server/src/server/waiting_list_ll.c File Reference
waiting_list_ll.c File Reference
#include "../../include/struct_server.h"
#include "../../include/get_instance.h"
#include "../../include/server.h"
Functions
int add_to_waiting_list (int new_socket, const char *team)
Function that add the client to the waiting list.
Function Documentation
add_to_waiting_list()
int add_to_waiting_list (int new_socket, const char * team)
Function that add the client to the waiting list.
Parameters
int new_socket the socket of the new client.
int index the index of the team.
will add the client to the waiting list.
Returns
return 0 if everything's good or 84 if an error occured.
Definition at line 17 of file waiting_list_ll.c.
 {
     server_t *server = get_instance();
     waiting_client_t *new_waiting_client = malloc(sizeof(waiting_client_t));
     if (new_waiting_client == NULL) {
         perror("malloc");
         close(new_socket);
         return 84;
     }
     new_waiting_client->socket = new_socket;
     new_waiting_client->team = strdup(team);
     if (new_waiting_client->team == NULL) {
         perror("strdup");
         close(new_socket);
         free(new_waiting_client);
         return 84;
     }
     TAILQ_INSERT_TAIL(&server->waiting_list, new_waiting_client, entries);
     return 0;
 }
References get_instance(), server, and team.
Referenced by handle_team_full(), and Test().